import type {
  AppState,
  ArchiveData,
  CalendarEvent,
  ConstitutionSection,
  GeotingCase,
  LexiconEntry,
  OldSlowGeoRecord,
  Party,
  Player,
} from "@/lib/types";

export const players: Player[] = [
  {
    id: "alf",
    name: "Alf Kåre Dalsbø",
    shortName: "Alf Kåre",
    partyId: "ss",
    color: "#1C2E4A",
    title: "Institusjonsbygger",
    specialty: "Sannhetssøk, sentrumsstrategier og embetsverk",
    strengths: "Strategisk, sannhetsdrevet og farlig glad i struktur.",
    weaknesses: "Kan bli for opptatt av å kontrollere før han fornyer.",
    moment: "Grunnla SS og gjorde riksregisteret til et politisk våpen.",
    mark: "Sannheten er viktigere enn makt, men makt kan brukes administrativt.",
  },
  {
    id: "vegard",
    name: "Vegard Lofnes",
    shortName: "Vegard",
    partyId: "ira",
    color: "#2E4E7E",
    title: "Grunnlovsverner",
    specialty: "Konstitusjonell bremsing og prinsipiell motstand",
    strengths: "Prinsipiell, konsekvent og vanskelig å flytte uten vedtak.",
    weaknesses: "Velger heller krig enn koalisjon med PLO.",
    moment: "Grunnla IRA for å beskytte 7/7-kravet mot impulsiv reformiver.",
    mark: "Praesidio constitutionis a morte.",
  },
  {
    id: "jorgen",
    name: "Jørgen Deem",
    shortName: "Jørgen",
    partyId: "plo",
    color: "#4A7C2E",
    title: "Pepsi Sjeik Nub Barack av PLO",
    specialty: "Poengliberalisme og intensjonsprinsipper",
    strengths: "Fleksibel, rettferdighetsorientert og svak for poengunderklassen.",
    weaknesses: "Mistenker alt som ligner et skjema.",
    moment: "Løftet poengunderklassens rettigheter inn i rikspolitikken.",
    mark: "Loven tjener geoten, ikke omvendt.",
  },
  {
    id: "steinar",
    name: "Steinar Lofnes",
    shortName: "Steinar",
    partyId: "pkk",
    color: "#7C2E2E",
    title: "Sultan / Thorn Offer",
    specialty: "Konflikttenning og regeldebatt",
    strengths: "Initiativrik, reformvillig og aldri tom for forslag.",
    weaknesses: "Krangler tidvis for kranglingens egen majestetiske skyld.",
    moment: "Grunnla PKK og befestet konfliktismen som statsbærende uro.",
    mark: "Alle vet hvor PKK står: i neste diskusjon.",
  },
  {
    id: "sverre",
    name: "Sverre Skilbreid",
    shortName: "Sverre",
    partyId: "cip",
    color: "#5C3E1A",
    title: "Cisterienserindianer",
    specialty: "Enkelthet, rytme, jord og himmel",
    strengths: "Kontemplativ, stabil og jordnær.",
    weaknesses: "Har offisiell unntaksstatus, noe som alltid må tolkes varsomt.",
    moment: "Ble stående som den mystiske roen i en ellers støyende republikk.",
    mark: "Rosehagen skal holdes i hevd.",
  },
  {
    id: "fredrik",
    name: "Fredrik Skoglund",
    shortName: "Fredrik",
    partyId: "mossad",
    color: "#2E2E2E",
    title: "Diskusjonsmotstander",
    specialty: "Effektivisering og psykologisk påvirkning",
    strengths: "Får ting til å gå fortere bare ved å se trøtt ut.",
    weaknesses: "Vil ikke diskutere, noe som er krevende i Geotia.",
    moment: "Grunnla MOSSAD og gjorde mindre prat til en kampsak.",
    mark: "Mer spill, mindre diskusjon.",
  },
  {
    id: "ruben",
    name: "Glenn Ruben Furu-Borgen",
    shortName: "Glenn Ruben",
    partyId: "pwp",
    color: "#7C5E1A",
    title: "Pølseminister",
    specialty: "Direkteaksjon, pragmatisme og saker over bordet",
    strengths: "Handlekraftig, rettferdighetsorientert og allergisk mot utsettelser.",
    weaknesses: "Kan behandle demokratiske prosesser som en unødvendig omvei.",
    moment: "Grunnla PWP og satte pølser og whiskey inn i statsapparatet.",
    mark: "JA til nei, og BORT med vekk.",
  },
];

export const parties: Party[] = [
  {
    id: "ss",
    name: "SS - Sannhetssøkende Sentrumsekstremister",
    leader: "Alf Kåre Dalsbø",
    motto: "Kontrollere for å fornye og bevare",
    ideology: "Kontrollisme",
    agenda:
      "Bevare Geos sjel, fornye uttrykket og la sannheten stå igjen etter diskusjonens lutringsild.",
    allies: "Blokkuavhengig, men alltid nær sentrum av alt.",
    rivals: "Alle som står i veien for sannheten.",
    comment:
      "Partiet forsøker å være konservativ grunnlovsbevarer, liberal poengforkjemper og progressiv fornyer samtidig.",
    color: "#1C2E4A",
    asset: "/geotia-assets/party-ss.png",
  },
  {
    id: "pkk",
    name: "PKK - Det Progressive KrangleKalifat",
    leader: "Steinar Lofnes / Thorn Offer",
    motto: "Krangling for kranglingens skyld",
    ideology: "Konfliktisme",
    agenda:
      "Stadig debatt, nye regler og hard justis mot navneforslag som viser seg å være druer.",
    allies: "Den som er villig til å krangle akkurat nå.",
    rivals: "Stillstand, ro og partikontorer med dårlig sikring.",
    comment: "Alle vet hvor de har PKK. Det er hele poenget.",
    color: "#7C2E2E",
    asset: "/geotia-assets/party-pkk.png",
  },
  {
    id: "plo",
    name: "PLO - PoengLiberales Organisasjon",
    leader: "Jørgen Deem",
    motto: "Loven tjener mennesket, ikke omvendt",
    ideology: "Regelfleksibilisme",
    agenda:
      "Færre regler, mer intensjon, og bedre vilkår for alle i poengunderklassen.",
    allies: "Pragmatiske geoter og alle som er lei av byråkrati.",
    rivals: "IRA og ekstreme grunnlovstolkninger.",
    comment:
      "PLO setter perifere landemerker og kulturelle assosiasjoner høyere enn streng bokstavtro.",
    color: "#4A7C2E",
    asset: "/geotia-assets/party-plo.png",
  },
  {
    id: "ira",
    name: "IRA - Ingen Reell Alternering",
    leader: "Vegard Lofnes",
    motto: "Beskytt grunnloven ved døden",
    ideology: "Ytterliggående grunnlovsbevaring",
    agenda:
      "Hindre impulsive endringer som setter SlowGeos kjerne i spill.",
    allies: "SS ved behov.",
    rivals: "PLO. Aldri koalisjon. Aldri fred uten protokoll.",
    comment: "Fungerer som konservativ brems når rikets reformiver blir for ivrig.",
    color: "#2E4E7E",
    asset: "/geotia-assets/party-ira.png",
  },
  {
    id: "mossad",
    name: "MOSSAD - Må Orke Spesielle, Slitsomme, Alternative Derivasjoner",
    leader: "Fredrik Skoglund",
    motto: "Mer spill, mindre diskusjon",
    ideology: "Effektivisme",
    agenda:
      "Psykologisk påvirkning av andre partier til politisk selvskading og kortere møter.",
    allies: "Alle som trykker start før debatten åpnes.",
    rivals: "Alle som sier 'bare ett poeng til'.",
    comment: "MOSSAD er Geotias korte sukk i møte med endeløs saksbehandling.",
    color: "#2E2E2E",
    asset: "/geotia-assets/party-mossad.png",
  },
  {
    id: "cip",
    name: "CIP - Cisterienserindianerpartiet",
    leader: "Sverre Skilbreid",
    motto: "Enkelthet, kontinuitet og rytme",
    ideology: "Jordbruksgeotisme",
    agenda:
      "Rustikk poengfordeling, rosehage i hevd og tidebønn uten fallende kammertone.",
    allies: "Rytmen, jorden og de gode rammene.",
    rivals: "Alt som forstyrrer enkelheten.",
    comment: "CIP er roen som gjør at staten ikke bare blir et krisemøte.",
    color: "#5C3E1A",
    asset: "/geotia-assets/party-cip.png",
  },
  {
    id: "pwp",
    name: "PWP - Pølser og Whiskey-Partiet",
    leader: "Glenn Ruben Furu-Borgen",
    motto: "JA til nei, og BORT med vekk",
    ideology: "Beslutningspopulisme",
    agenda:
      "Ting må gjøres, helst straks og gjerne før noen rekker å opprette komite.",
    allies: "Alle som vil ha ting gjort.",
    rivals: "Endeløse diskusjoner som ender i ingenting.",
    comment:
      "Rettferdighet der det er for mye urettferdighet og omvendt.",
    color: "#7C5E1A",
    asset: "/geotia-assets/party-pwp.png",
  },
];

const constitution: ConstitutionSection[] = [
  {
    paragraph: "§ 1",
    title: "Frister og spillrammer",
    body: [
      "Tidsrom for frist er 10:00-23:00.",
      "Hvert spill må ha minst 1 times frist.",
      "Fristen rundes opp til nærmeste kvarter.",
      "Fristen kan forkortes når alle geoter har svart.",
      "Det er bildets ankomst som avslutter runden, ikke fristen.",
    ],
  },
  {
    paragraph: "§ 2",
    title: "Deltakelse",
    body: [
      "Minimum antall deltakere i en tellende SlowGeo-runde er fem geoter.",
      "Ikke deltatt og ugyldig svar gir 0 poeng.",
      "Passiv geografisk desertering fritar ingen fra kattometeret.",
    ],
  },
  {
    paragraph: "§ 3",
    title: "Avgitt svar",
    body: [
      "Siste svar gjelder.",
      "Alle svar må ha utgangspunkt i et konkret sted, med valgfrie presiseringer.",
      "Sverre har unntak fra denne regelen, som seg hør og bør.",
      "Frukt, bær, grønnsaker og andre ikke-geografiske ting gir 0 poeng.",
    ],
  },
  {
    paragraph: "§ 4",
    title: "Poengfordeling",
    body: [
      "Nærmest riktig sted får 7 poeng, deretter 6, 5, 4, 3, 2 og 1.",
      "Delt plassering gir poengsummen til den delte plasseringen.",
      "Poeng viser plasseringsevne, ikke nødvendigvis sjelero.",
    ],
  },
  {
    paragraph: "§ 5",
    title: "Kattometeret",
    body: [
      "Kattometeret summerer antall kilometer geoten bommer med.",
      "Lavest kattometer er best.",
      "Ikke-deltakere og ugyldige svar får tellende km lik snittet av de tre dårligste gyldige km-resultatene i runden.",
      "Kattometeret må aldri undergraves av passiv geografisk desertering.",
    ],
  },
  {
    paragraph: "§ 6",
    title: "GeoKodeksen",
    body: [
      "Vi resonnerer høyt, og alle tanker deles.",
      "Ingen informasjon holdes tilbake fra en medgeot.",
      "Vi konkurrerer, men lar aldri en geot falle utenfor.",
    ],
  },
  {
    paragraph: "§ 7",
    title: "GeoTinget",
    body: [
      "Endringer i GeoGrunnloven krever konsensus.",
      "Mindre lovendringer kan vedtas med rent flertall blant geomentarikerne.",
      "Alle prinsipielle krangler kan løftes til GeoVAR når æren krever det.",
    ],
  },
];

const code = [
  "Vi resonnerer høyt, og alle tanker deles.",
  "Alle hint deles. Ingen informasjon holdes tilbake fra en medgeot.",
  "Vi konkurrerer, men vi lar aldri en geot falle utenfor.",
  "En geot får aldri dra til India uten å få klar beskjed.",
  "Vi latterliggjør den som stikker bort fra flokken, og vi river ned den som hever seg over resten.",
  "En geot kan alltid gjenreise sin ære ved å argumentere godt og stikke hardt mot andre geoter.",
  "Man kan bli ekspert på et hvilket som helst felt. Førstemann til mølla, men andre geoter kan ta opp kampen.",
];

const lexicon: LexiconEntry[] = [
  {
    term: "Geotia",
    definition:
      "Riket, universet og statsapparatet som oppstod da geografi, vennskap og intern maktkamp ble institusjonalisert.",
    origin: "Grunnfortellingen",
    example: "Geotia krever protokoll før runden kan låses.",
    comment: "Ikke bare en gruppe som spiller geografi. En sivilisasjon.",
    category: "Riket",
  },
  {
    term: "Geot",
    definition: "Statsborger, deltaker og medbærer av den geotiske byrde.",
    origin: "Geotia",
    example: "En sann geot deler hint før han feiler.",
    comment: "Brukes om alle syv.",
    category: "Riket",
  },
  {
    term: "Geotisme",
    definition:
      "Den nasjonale grunnideen: at verden kan forstås gjennom kart, stikk, mønstre og høylytt resonnering.",
    origin: "Nasjonalideologien",
    example: "Geotismen krever at du sier tanken høyt.",
    comment: "Statsideologi og sosial lim.",
    category: "Riket",
  },
  {
    term: "SlowGeo",
    definition:
      "Spillformen der geotene tipper et sted og rangeres etter avstand fra fasit.",
    origin: "1. januar",
    example: "SlowGeo i kveld, embetsverket er varslet.",
    comment: "Grunnspillet og tidsregningen.",
    category: "Spill",
  },
  {
    term: "Kattometeret",
    definition:
      "Akkumulert bom i kilometer. Navnet kommer fra magefølelse, ikke faktisk katt.",
    origin: "Intern følelse som ble statsinstitusjon",
    example: "Han leder poeng, men kattometeret lukter grunnlovskrise.",
    comment: "Lavest er best. Desertering straffes automatisk.",
    category: "Spill",
  },
  {
    term: "GeoTinget",
    definition:
      "Geotias lovgivende, kranglende og mytedannende forsamling.",
    origin: "15. januar",
    example: "Dette må til GeoTinget før PLO tolker det fritt.",
    comment: "Både parlament og sosialt trykkammer.",
    category: "Institusjon",
  },
  {
    term: "GeoVAR",
    definition:
      "Kontrollorganet som etterprøver tvilstilfeller, ære og mulige lovbrudd.",
    origin: "2. februar",
    example: "Send den til GeoVAR før stemningen kollapser.",
    comment: "Høy symbolverdi, varierende saksbehandlingstid.",
    category: "Institusjon",
  },
  {
    term: "GeoKodeksen",
    definition:
      "Geotias moralske og sosiale normverk for deling, stikk og kollektiv sannhetssøk.",
    origin: "Tradisjonen",
    example: "GeoKodeksen sier at hintet skal deles.",
    comment: "Rikets uskrevne lov som selvsagt er skrevet ned.",
    category: "Institusjon",
  },
  {
    term: "Å ta en India",
    definition:
      "En panisk avgjørelse i siste liten som ender betydelig dårligere enn utgangspunktet.",
    origin: "Klassisk feilslag",
    example: "Han tok en India og byttet kontinent med full selvtillit.",
    comment: "Akutt varsel om kollektiv korrigering.",
    category: "Uttrykk",
  },
  {
    term: "Å ta en Sarajevo",
    definition: "Å være svært selvsikker, gå ekstremt høyt ut og treffe blink.",
    origin: "Sarajevodagen",
    example: "Det var en ren Sarajevo.",
    comment: "Heroisk, men farlig for ydmykheten.",
    category: "Uttrykk",
  },
  {
    term: "Å ta en El Tari",
    definition: "Å google svaret og lure Geotia.",
    origin: "El Tari Airport-hendelsen",
    example: "GeoVAR lukter El Tari.",
    comment: "Moralsk tvilsom praksis.",
    category: "Uttrykk",
  },
  {
    term: "Geopagos",
    definition:
      "Det mytiske stedet der de gamle geosofene la ut sin geosofi hele dagen.",
    origin: "Forhistorien",
    example: "Som i de gamle dager på Geopagos.",
    comment: "Halvmytisk, helnyttig.",
    category: "Riket",
  },
  {
    term: "Damer på sykler",
    definition: "Nederlandsk varseltegn.",
    origin: "Referanselæren",
    example: "Damer på sykler: Nederland er innkalt.",
    comment: "Ikke juridisk bindende, men ofte nok.",
    category: "Kjennetegn",
  },
  {
    term: "Gule skilter bak, hvite foran",
    definition: "Typisk UK.",
    origin: "Skiltologi",
    example: "Gule bak og hvite foran: dette er ikke Sør-Amerika.",
    comment: "En av de mer solide læresetningene.",
    category: "Kjennetegn",
  },
  {
    term: "Stolper i betong",
    definition: "Frankrike. Eventuelt begynnelsen på en krangel.",
    origin: "Stolpologi",
    example: "Betongstolpene peker mot Frankrike.",
    comment: "Hull kan flytte saken mot Polen eller Romania.",
    category: "Kjennetegn",
  },
  {
    term: "Hvis USA er feil",
    definition: "Da kan det være Canada.",
    origin: "Indianerkjennetegn",
    example: "Det er USA, men noe er feil. Altså Canada.",
    comment: "En setning som både hjelper og ødelegger.",
    category: "Kjennetegn",
  },
  {
    term: "Petit verdot",
    definition: "En drue, ikke et sted i Frankrike.",
    origin: "Navnefadese",
    example: "GeoVAR avviser Petit verdot som geografisk svar.",
    comment: "Hard justis mot frukt og bær.",
    category: "Advarsel",
  },
  {
    term: "Det går alltid oppover i Peru",
    definition: "Terrenglære med høy indre sannhetsfølelse.",
    origin: "Geotisk kunnskapslære",
    example: "Veien stiger. Peru melder seg.",
    comment: "Ikke kartgaranti.",
    category: "Kjennetegn",
  },
  {
    term: "Er det utsikt, er det Bolivia",
    definition: "Overlevert høylandsheuristikk.",
    origin: "Geotisk kunnskapslære",
    example: "Utsikt nok til et postkort. Bolivia.",
    comment: "Kan også være feil på vakker måte.",
    category: "Kjennetegn",
  },
  {
    term: "Elektrosjokk-bokstaver",
    definition: "Hvis bokstavene ser ut som elektrosjokk, kan det være Polen.",
    origin: "Skriftspråklæren",
    example: "Dette alfabetet er stresset. Polen?",
    comment: "Språklig presisjon under utvikling.",
    category: "Kjennetegn",
  },
];

const calendar: CalendarEvent[] = [
  {
    date: "1. januar",
    name: "SlowGeos fødselsdag",
    category: "Høytid",
    description: "Dagen geotene virkelig kom til liv.",
    significance: "Startpunkt for tidsregning og selvforståelse.",
  },
  {
    date: "14. januar",
    name: "Pinot Noir-dagen",
    category: "Grunnlov",
    description: "Dagen GeoGrunnloven ble befestet.",
    significance: "En påminnelse om at druer ikke er geografiske steder.",
  },
  {
    date: "15. januar",
    name: "GeoTinget ble opprettet",
    category: "Institusjon",
    description: "Rikets lovgivende og kranglende forsamling fikk form.",
    significance: "Statsapparatet fikk stemme, bord og saksliste.",
  },
  {
    date: "15. januar",
    name: "Geotia City grunnlagt",
    category: "Riket",
    description: "Hovedstadens symbolske grunnleggelse.",
    significance: "Alle veier leder til Geotia City, særlig når ingen vet hvor veien er.",
  },
  {
    date: "16. januar",
    name: "Geokrati-dagen",
    category: "Politikk",
    description: "Alle geoter representert i et parti.",
    significance: "Riket fikk full partipolitisk overbygning.",
  },
  {
    date: "21. januar",
    name: "Partikontorets dag",
    category: "Konflikt",
    description: "Dagen da SS sprengte partikontoret til PKK i loretradisjonen.",
    significance: "Et symbol på at debattkultur bør ha brannrutiner.",
  },
  {
    date: "31. januar",
    name: "Første GeoTing",
    category: "Institusjon",
    description: "Første formelle tingdag.",
    significance: "Saksbehandlingens høytid.",
  },
  {
    date: "2. februar",
    name: "Første GeoVAR",
    category: "Institusjon",
    description: "Kontrollinstansen trådte inn i historien.",
    significance: "Rettferdighetens sakte men prinsipielle lys.",
  },
  {
    date: "6. februar",
    name: "Botswana-dagen",
    category: "Hendelse",
    description: "Dagen med adling av Ingebjørg.",
    significance: "Bevis på at Geotia kan gjøre små øyeblikk til annaler.",
  },
  {
    date: "9. februar",
    name: "Byvandringsdagen",
    category: "Hendelse",
    description: "Dagen geotene vandret hvileløst rundt i Wien for å finne svaret.",
    significance: "Et varig monument over geografisk uro.",
  },
  {
    date: "24. mai",
    name: "Antiklimaksdagen",
    category: "Hendelse",
    description: "Progreso vs. Nuevo Progreso + El Tari Airport.",
    significance: "Et kapittel i skuffelsens og kontrollens historie.",
  },
  {
    date: "26. mai",
    name: "Sarajevodagen",
    category: "Høytid",
    description: "Dagen geo nesten døde.",
    significance: "Minnes med ærefrykt og forsiktig selvtillit.",
  },
];

const geotingCases: GeotingCase[] = [
  {
    date: "Udatert",
    caseName: "Forsinket SlowGeo-feiring",
    proposal: "Vi burde ha en forsinket feiring i forbindelse med SlowGeos fødselsdag.",
    proposedBy: "Innkomne forslag",
    decision: "Ikke behandlet",
    votes: "-",
    status: "Til GeoTinget",
    comment: "Embetsverket har notert saken uten å love kake.",
  },
  {
    date: "Udatert",
    caseName: "Grunnlovsdagskomiteen",
    proposal: "Opprette en komite som kan planlegge grunnlovsdagen til Geotia.",
    proposedBy: "Innkomne forslag",
    decision: "Ikke behandlet",
    votes: "-",
    status: "Til komite",
    comment: "En komite for å planlegge en dag om regler er svært geotisk.",
  },
  {
    date: "Løpende",
    caseName: "Kattometerets integritet",
    proposal:
      "Ikke-deltakelse skal gi tellende km lik snittet av de tre dårligste gyldige resultatene.",
    proposedBy: "Riksregisteret",
    decision: "Innført i appen",
    votes: "Embetsvedtak",
    status: "Iverksatt",
    comment: "Passiv geografisk desertering er ikke lenger et smutthull.",
  },
];

const oldSlowGeo: OldSlowGeoRecord[] = [
  { player: "Alf Kåre", points: 84, pointRounds: 18, kattometer: 12104, kattometerRounds: 18 },
  { player: "Fredrik", points: 106, pointRounds: 19, kattometer: 10592, kattometerRounds: 19 },
  { player: "Jørgen", points: 17, pointRounds: 3, kattometer: 629, kattometerRounds: 3 },
  { player: "Sverre", points: 41, pointRounds: 10, kattometer: 8227, kattometerRounds: 11 },
  { player: "Steinar", points: 77, pointRounds: 18, kattometer: 12909, kattometerRounds: 18 },
  { player: "Vegard", points: 87, pointRounds: 19, kattometer: 13720, kattometerRounds: 18 },
  { player: "Ruben", points: 83, pointRounds: 18, kattometer: 13666, kattometerRounds: 18 },
];

export const archive: ArchiveData = {
  constitution,
  code,
  lexicon,
  calendar,
  geotingCases,
  oldSlowGeo,
  geosophy: [
    "Den som vet hvor han er, vet ikke nødvendigvis hvor andre er.",
    "Motoren enkel. Overbygningen rik.",
    "Staten må ikke bli så byråkratisk at ingen møter opp til embetsverket.",
    "En geot får aldri dra til India uten å få klar beskjed.",
    "Når veien er uklar, følger vi kompasset i hjertet og tabellen i riksregisteret.",
    "Kattometeret glemmer ikke, men det fører protokoll med verdighet.",
  ],
};

export const initialState: AppState = {
  players,
  parties,
  archive,
  rounds: [],
};
