import type {
  AppState,
  ArchiveData,
  ArchiveEpisode,
  CalendarEvent,
  CanonSection,
  ConstitutionSection,
  GameDefinition,
  GeotingCase,
  KnowledgeGroup,
  KonespillRule,
  LexiconEntry,
  OldSlowGeoRecord,
  Party,
  Player,
} from "@/lib/types";

export const games: GameDefinition[] = [
  {
    id: "slowgeo",
    name: "SlowGeo",
    shortName: "SlowGeo",
    description:
      "Bilde sendes i egen samtaletråd, geotene gjetter sted, og kilometeren blir ført med full tyngde.",
    scoreLabel: "Km fra fasit",
    scoreHelp: "Lavest km er best. Appen bruker egen kattometerlov for SlowGeo.",
    scoreDirection: "lower",
    ritual: "Samtaletråd, frist, bilde, fasit og skammens avstand.",
    color: "#062b40",
  },
  {
    id: "geo",
    name: "Geo",
    shortName: "Geo",
    description:
      "Geotene møtes fysisk eller digitalt og spiller GeoGuessr sammen i sanntid.",
    scoreLabel: "GeoGuessr-score",
    scoreHelp: "Høyest score er best. Før totalscore eller avtalt rundescore.",
    scoreDirection: "higher",
    ritual: "Felles rom, felles rop, individuell ære.",
    color: "#194832",
  },
  {
    id: "maptap",
    name: "MapTap",
    shortName: "MapTap",
    description:
      "Ny daglig kartlek der geotene tapper seg mot riktig sted og må leve med avstanden.",
    scoreLabel: "MapTap-score",
    scoreHelp: "Høyest score er best. Før dagens poengscore slik spillet viser den.",
    scoreDirection: "higher",
    ritual: "Trykk på kloden, lat som hånden visste mer enn hodet.",
    color: "#7c2430",
  },
  {
    id: "satle",
    name: "Satle",
    shortName: "Satle",
    description:
      "Satellitt- og landgjetting i daglig format. Færrest forsøk gir mest verdighet.",
    scoreLabel: "Antall forsøk",
    scoreHelp: "Lavest antall forsøk er best. Bruk 0/ugyldig om riket kollapset.",
    scoreDirection: "lower",
    ritual: "Se, gjett, benekt, gjett igjen.",
    color: "#5C3E1A",
  },
  {
    id: "globle",
    name: "Globle",
    shortName: "Globle",
    description:
      "Dagens landjakt der varme og kalde hint sakte avslører hvor verden egentlig lå.",
    scoreLabel: "Antall forsøk",
    scoreHelp: "Lavest antall forsøk er best.",
    scoreDirection: "lower",
    ritual: "Fargekartet hvisker, geoten overvurderer seg selv.",
    color: "#2E4E7E",
  },
];

export const players: Player[] = [
  {
    id: "alf",
    name: "Alf Kåre Dalsbø",
    shortName: "Alf Kåre",
    partyId: "ss",
    color: "#1C2E4A",
    title: "Institusjonsbygger",
    specialty: "Sannhetssøk, sentrumsstrategier og embetsverk",
    strengths: "Strategisk, sannhetsdrevet og farlig glad i struktur.",
    weaknesses: "Kan bli for opptatt av å kontrollere før han fornyer.",
    moment: "Grunnla SS og gjorde statsarkivet til et politisk våpen.",
    mark: "Sannheten er viktigere enn makt, men makt kan brukes administrativt.",
  },
  {
    id: "vegard",
    name: "Vegard Lofnes",
    shortName: "Vegard",
    partyId: "ira",
    color: "#2E4E7E",
    title: "Grunnlovsverner",
    specialty: "Konstitusjonell bremsing og prinsipiell motstand",
    strengths: "Prinsipiell, konsekvent og vanskelig å flytte uten vedtak.",
    weaknesses: "Velger heller krig enn koalisjon med PLO.",
    moment: "Grunnla IRA for å beskytte 7/7-kravet mot impulsiv reformiver.",
    mark: "Praesidio constitutionis a morte.",
  },
  {
    id: "jorgen",
    name: "Jørgen Deem",
    shortName: "Jørgen",
    partyId: "plo",
    color: "#4A7C2E",
    title: "Pepsi Sjeik Nub Barack av PLO",
    specialty: "Poengliberalisme og intensjonsprinsipper",
    strengths: "Fleksibel, rettferdighetsorientert og svak for poengunderklassen.",
    weaknesses: "Mistenker alt som ligner et skjema.",
    moment: "Løftet poengunderklassens rettigheter inn i rikspolitikken.",
    mark: "Loven tjener geoten, ikke omvendt.",
  },
  {
    id: "steinar",
    name: "Steinar Lofnes",
    shortName: "Steinar",
    partyId: "pkk",
    color: "#7C2E2E",
    title: "Sultan og KrangleKalif av PKK",
    specialty: "Konflikttenning og regeldebatt",
    strengths: "Initiativrik, reformvillig og aldri tom for forslag.",
    weaknesses: "Krangler tidvis for kranglingens egen majestetiske skyld.",
    moment: "Grunnla PKK og befestet konfliktismen som statsbærende uro.",
    mark: "Alle vet hvor PKK står: i neste diskusjon.",
  },
  {
    id: "sverre",
    name: "Sverre Skilbreid",
    shortName: "Sverre",
    partyId: "cip",
    color: "#5C3E1A",
    title: "Cisterienserindianer",
    specialty: "Enkelthet, rytme, jord og himmel",
    strengths: "Kontemplativ, stabil og jordnær.",
    weaknesses: "Har offisiell unntaksstatus, noe som alltid må tolkes varsomt.",
    moment: "Ble stående som den mystiske roen i en ellers støyende republikk.",
    mark: "Rosehagen skal holdes i hevd.",
  },
  {
    id: "fredrik",
    name: "Fredrik Skoglund",
    shortName: "Fredrik",
    partyId: "mossad",
    color: "#2E2E2E",
    title: "Diskusjonsmotstander",
    specialty: "Effektivisering og psykologisk påvirkning",
    strengths: "Får ting til å gå fortere bare ved å se trøtt ut.",
    weaknesses: "Vil ikke diskutere, noe som er krevende i Geotia.",
    moment: "Grunnla MOSSAD og gjorde mindre prat til en kampsak.",
    mark: "Mer spill, mindre diskusjon.",
  },
  {
    id: "ruben",
    name: "Glenn Ruben Furu-Borgen",
    shortName: "Glenn Ruben",
    partyId: "pwp",
    color: "#7C5E1A",
    title: "Pølseminister",
    specialty: "Direkteaksjon, pragmatisme og saker over bordet",
    strengths: "Handlekraftig, rettferdighetsorientert og allergisk mot utsettelser.",
    weaknesses: "Kan behandle demokratiske prosesser som en unødvendig omvei.",
    moment: "Grunnla PWP og satte pølser og whiskey inn i statsapparatet.",
    mark: "JA til nei, og BORT med vekk.",
  },
  {
    id: "danny",
    name: "Danny",
    shortName: "Danny",
    partyId: "",
    username: "danny",
    role: "tingvitne",
    canCompete: true,
    canVote: false,
    color: "#5b4a7d",
    title: "Tingvitne",
    specialty: "Tribunenærvær, ordensvei under oppføring og kontrollert ikke-stemmegivning",
    strengths: "Kan overvære krangling uten å bli tildelt komiteansvar.",
    weaknesses: "Mangler foreløpig parti og må derfor sitte på benken mens riket stemmer.",
    moment: "Tok plass som Geotias første offisielle Tingvitne.",
    mark: "Har adgang til tingvollen, men ikke til stemmeurnen eller partistiftelse før nivå 7 er fortjent.",
  },
];

export const competingPlayers = players.filter((player) => player.canCompete !== false);
export const geotingVoters = players.filter((player) => player.canVote !== false);
export const tingvitner = players.filter((player) => player.role === "tingvitne");

export function isVotingPlayerId(playerId: string) {
  return geotingVoters.some((player) => player.id === playerId);
}

export const parties: Party[] = [
  {
    id: "ss",
    name: "SS - Sannhetssøkende Sentrumsekstremister",
    leader: "Obergruppenführer Alf Kåre Dalsbø",
    motto: "Kontrollere for å fornye og bevare!",
    ideology: "Machtsteuerunglebensraum (Kontrollisme)",
    agenda:
      "Bevare Geos sjel, men stadig fornye dets uttrykk. Hard ærlig diskusjon som lutringsild. Sentrum kontrolleres og utvides.",
    allies: "Blokkuavhengig. Tar det beste fra alle sider.",
    rivals: "Ingen faste, men sannheten er viktigere enn makt.",
    comment:
      "Kombinerer konservatisme, liberal poengkamp og progressiv fornyelse. Sannhet viktigere enn makt.",
    color: "#1C2E4A",
    asset: "/geotia-assets/party-ss.png",
    manifesto: [
      "Vår hovedsak er å alltid bevare Geos sjel, men stadig fornye dets uttrykk. Vi vil bevare geotnisiteten, men vi er meget for inntrykk fra andre geokulturer.",
      "Vi verdsetter intensjon høyt, men mener ordningene og rammene er nødvendig for bevare og fornye geosamfunnet. Dette skal skje ved rå og ærlige diskusjoner der sannheten alltid står igjen på slagmarken som enslig seierherre.",
      "Vi står i mellom PoengLiberales Organisasjon og De Progressives GeoParti, fordi vi mener det er i som er best i stand til å ta det beste fra begge sider.",
      "Vi er en garantist for sannheten ved at vi klarer spenningen mellom ulike sannheter. Vi er et blokkuavhengig parti som gjør hva som helst for å så sannheten frem i lyset. Det er viktigere enn makt.",
      "Derfor kan velgerne stole på oss. Ingen vet hva sannheten er før røyken har lagt seg på slagmarken. Det som har blitt lutret gjennom den ilden og fortsatt består, DET er sannheten!",
      "Hos SS finner du den konservative grunnlovsbevareren, den liberale poengforkjemperen og den progressive fornyeren.",
    ],
    doctrine: [
      "Sentrum må kontrolleres, og så utvides. Livet (spillet) må kontrolleres.",
      "Livet (spillet) formes og leves (spilles) best innenfor rammene og ordningene satt opp og beskyttet av SS.",
      "Alt skal, med makt om nødvendig, føres inn i disse rammene. Et liv (spill) levd (spilt) i lydighet gir det beste jordsmonn for lykke og et lykkelig folk gir (SS-)staten stor styrke.",
      "Vi bevarer rammene og fornyer jordsmonnet.",
    ],
  },
  {
    id: "pkk",
    name: "PKK - Det Progressive KrangleKalifat",
    leader: "Sultan og KrangleKalif Steinar Lofnes av PKK",
    motto: "Krangling for kranglingens skyld!",
    ideology: "Konfliktisme",
    agenda:
      "Stadig debatt og nye regler. Anti-stillstand, anti-ro. Hard justis mot navneforslag som er druer eller frukt.",
    allies: "Bevegelige - krangler med alle.",
    rivals: "SS (sprengt partikontoret 21. januar).",
    comment: "Alle vet hvor de har PKK. Forandring for forandringens skyld.",
    color: "#7C2E2E",
    asset: "/geotia-assets/party-pkk.png",
    manifesto: [
      "De progressives viktigste sak er at det en hver tid bør være diskusjon og progresjon. Nye regler bør stadig debatteres og legges til for å holde spillet levende.",
      "Vi er imot lover som gjør endring vanskelig og ønsker hard justis mot navneforslag som viser seg å være druer eller andre typer frukt og bær.",
      "Alle vet hvor de har oss. En stemme på PKK betyr krangling for kranglingens skyld og forandring forandringens skyld. Vi kommer aldri til å vike fra det!",
    ],
  },
  {
    id: "plo",
    name: "PLO - PoengLiberales Organisasjon",
    leader: "Jørgen Deem / Pepsi Sjeik Nub Barack av PLO",
    motto: "Loven tjener mennesket, ikke omvendt",
    ideology: "Liberalisme / Regelfleksibilisme",
    agenda:
      "Færre regler, mer fleksibilitet. Intensjon over bokstav. Åpne for geo på ugunstige tidspunkt for elitene.",
    allies: "Åpen for pragmatiske allianser.",
    rivals: "IRA (prinsipielt fiendskap).",
    comment:
      "Kjemper for poengunderklassens rettigheter. Skeptiske til IRA og ekstreme grunnlovstolkninger.",
    color: "#4A7C2E",
    asset: "/geotia-assets/party-plo.png",
    manifesto: [
      "For et liberalt geosamfunn med færre regler og føringer. Kjemper for poengunderklassens rettigheter, og muligheter å komme seg opp og frem.",
      "Vi står på motsatt side av de Progressive og ønsker fleksible geo-løsninger og svar, som inkluderer perifere landemerker, kulturelle assosiasjoner og setter intensjon høyere enn bokstav.",
      "Etisk / Regel liberal. Loven tjener mennesket og ikke omvendt. Vi ønsker Mindre byråkrati (valg og diskusjoner) og færre lover.",
      "PLO er skeptiske til IRAs ekstreme forhold til grunnlov og regler.",
      "PLO er positive til gjennomføring av GEO på tidspunkt som er ugunstige for elitistene på toppen.",
    ],
  },
  {
    id: "ira",
    name: "IRA - Ingen Reell Alternering",
    leader: "Vegard Lofnes",
    motto: "Beskytt grunnloven ved døden; praesidio constitutionis a morte",
    ideology: "Ytterliggående grunnlovsbevaring",
    agenda:
      "Hindre impulsive endringer som truer spillets kjerne. 7/7 krav for fristen beskyttes for enhver pris.",
    allies: "SS (støtteparti ved behov).",
    rivals: "PLO - velger heller krig enn koalisjon.",
    comment: "Vil aldri gå i koalisjon med PLO. Fungerer som konservativt støtteparti.",
    color: "#2E4E7E",
    asset: "/geotia-assets/party-ira.png",
    manifesto: [
      "Har som grunnvisjon å være et ytterliggående grunnlovsbevarende parti som sentrumpartiet kan støtte seg på i enkeltssaker for å hindre impulsive endringer ved grunnloven som setter selve hovedkjernen i spillet i spill - at 7/7 må svare for at frist kan endres.",
      "Håpet er å gjøre de progressive overflødig, og står i ideologisk fiendskap med PLO.",
      "IRA velger heller krig enn samarbeid med PLO. IRA kommer aldri til å gå i koalisjon med PLO. IRA kan bidra til å tippe vektskålen i konservativ retning ved behov.",
    ],
  },
  {
    id: "mossad",
    name: "MOSSAD - Må Orke Spesielle, Slitsomme, Alternative Derivasjoner",
    leader: "Fredrik Skoglund",
    motto: "Mer spill, mindre diskusjon!",
    ideology: "Effektivisme / Psykologisk Manipulasjon",
    agenda:
      "Presse andre partier til politisk harakiri via psykologisk påvirkning. Mer spilling, mindre krangling.",
    allies: "Fleksible - bruker alle.",
    rivals: "Alle som diskuterer for mye.",
    comment: "MOSSAD står for psykisk påvirkning av de andre partiene.",
    color: "#2E2E2E",
    asset: "/geotia-assets/party-mossad.png",
    manifesto: [
      "Mer spill, mindre diskusjon!",
      "MOSSAD står for psykisk påvirkning av de andre partiene til å begå politisk harakiri!",
    ],
  },
  {
    id: "cip",
    name: "CIP - Cisterienserindianerpartiet",
    leader: "Cisterienserindianer Sverre Skilbreid",
    motto: "Enkelthet, kontinuitet og spillets gode livsbetingelser",
    ideology: "Jordbruksgeotisme / Kontemplativ rustisisme",
    agenda:
      "Rustikk poengfordeling. Rosehagen holdes i hevd. Neper og rotfrukter høstes i tide. Tidebønnene synges.",
    allies: "Nøytral - jordnær og kontemplativ.",
    rivals: "Alt som forstyrrer rytmen og enkelheten.",
    comment: "Opptatt av kontinuitet, repetisjon, rytme og enkle rammer. Sverre har unntak fra svarregel.",
    color: "#5C3E1A",
    asset: "/geotia-assets/party-cip.png",
    manifesto: [
      "Vi cisteriensere er med på rustikk poengfordeling i en enkel planting etter gode jordbruksprinsipp.",
      "Cisterienserpartiet står for enkelthet, kontinuitet, repetisjon, rytme, enkle rammer, og spillets frihet og gode livsbetingelser.",
      "Cisrerienserpartiet er opptatt av at rosehagen holdes i hevd, at neper og rotfrukter høstes i tide, at rikelig med urter tørkes og lagres på rett måte, og at tidebønnene synges uten at kammertonen faller.",
    ],
  },
  {
    id: "pwp",
    name: "PWP - Pølser og Whiskey-Partiet",
    leader: "Ruben Furu-Borgen",
    motto: "JA til nei, og BORT med vekk!",
    ideology: "Beslutningspopulisme / Direkteaksjonisme",
    agenda:
      "Ting må gjøres, gjerne umiddelbart og uten demokrati. Saker løses bedre over pølser og whiskey.",
    allies: "Alle som vil ha ting gjort.",
    rivals: "Endeløse diskusjoner som ender i ingenting.",
    comment:
      "Rettferdighet der det er for mye urettferdighet og omvendt. Med PWP får vi tingene gjort.",
    color: "#7C5E1A",
    asset: "/geotia-assets/party-pwp.png",
    manifesto: [
      "Vi står for pølser og whiskey.",
      "Med PWP får vi tingene gjort.",
      "Dersom ting ikke blir iverksatt med en gang, helst uten demokratisk avgjørelse, kan man like gjerne la vær!",
      "PWP står for rettferdighet der det er for mye urettferdighet og omvendt..",
      "Saker løses bedre over Pølser og Whiskey, enn over endeløse diskusjoner som ender i ingenting!",
      "Slagord: JA til nei, og BORT med vekk!",
    ],
  },
];

const constitution: ConstitutionSection[] = [
  {
    paragraph: "Preambel",
    title: "SpillNasjonen Geotia",
    body: [
      "Vi, de syv geograter i Geotia, fastsetter herved følgende grunnlov for SpillNasjonen Geotia og SlowGeo.",
      "Geotia er riket. Folket er geoter. Nasjonalideologien er geotisme.",
    ],
  },
  {
    paragraph: "§ 1",
    title: "Frister og spillrammer",
    body: [
      "Tidsrom for frist: 10:00-23:00.",
      "Hvert spill må ha minst 1 times frist.",
      "Fristen rundes opp til nærmeste kvarter.",
      "Fristen kan forkortes om alle geoter har svart (7/7).",
      "Det er bildets ankomst som avslutter runden, ikke fristen. Bildet kan ikke komme før fristen, men et svar kan komme etter fristen så lenge bildet ikke er sendt.",
      "Minimum antall deltakere: 5 geoter.",
    ],
  },
  {
    paragraph: "§ 2",
    title: "Lovendring",
    body: [
      "Endringer i GeoGrunnloven kan kun skje ved konsensus på GeoTinget (7/7).",
      "Alle geoter må ha avgitt stemme for at avstemningen skal være gyldig. Gjør din plikt, krev din rett Geoter!",
      "Mindre lovendringer kan vedtas ved rent flertall (4/7) blant geomentarikerne på GeoTinget.",
    ],
  },
  {
    paragraph: "§ 3",
    title: "Avgitt svar",
    body: [
      "Siste svar gjelder.",
      "Alle svar må ha utgangspunkt i et konkret sted, med valgfrie presiseringer som kilometer og himmelretninger.",
      "Sverre har unntak fra denne regelen.",
      "Om man kun svarer et land/en stat, uten videre presiseringer, blir svaret automatisk midt i landet/staten.",
      "Bare geografiske steder på jorden kan gi poeng. Frukt, bær, grønnsaker eller alle andre ting gir 0 poeng.",
      "Alle land deles i tre både vertikalt og horisontalt (sør-midt-nord og vest-midt-øst). Om noen bare sier for eksempel «nord» blir det målt fra midten av den øvre tredel.",
      "Himmelretninger er et område, ikke et punkt.",
    ],
  },
  {
    paragraph: "§ 4",
    title: "Poengfordeling",
    body: [
      "1. plass: 7p.",
      "2. plass: 6p.",
      "3. plass: 5p.",
      "4. plass: 4p.",
      "5. plass: 3p.",
      "6. plass: 2p.",
      "7. plass: 1p.",
      "Ikke deltatt/ikke godkjent svar: 0p.",
      "Delt plassering gir poengsummen til den delte plasseringen.",
    ],
  },
  {
    paragraph: "§ 5",
    title: "Kattometeret",
    body: [
      "Kattometeret legger sammen antall kilometer man bommer med. Den med færrest kilometer vinner.",
      "Kilometerne for den/de som ikke deltar er gjennomsnittet av de tre dårligste.",
      "Passiv geografisk desertering fritar ingen fra kattometeret.",
    ],
  },
  {
    paragraph: "§ 6",
    title: "GeoKodeksen",
    body: [
      "Vi resonnerer høyt, og alle tanker deles.",
      "Alle hint deles. Ingen informasjon holdes tilbake fra en medgeot.",
      "Vi konkurrerer, men vi lar aldri en geot falle utenfor.",
      "Om en geot foreslår et åpenbart feil sted blir han umiddelbart korrigert. En geot får aldri dra til India uten å få klar beskjed!",
      "Vi latterliggjør den som stikker bort fra flokken, og vi river ned den som hever seg over resten!",
      "En geot kan alltid gjenreise sin ære ved å argumentere godt og stikke hardt mot andre geoter.",
      "Man kan bli ekspert på et hvilket som helst felt. Førstemann til mølla. Men ekspertstatusen er aldri helt trygg.",
    ],
  },
  {
    paragraph: "§ 7",
    title: "GeoTinget",
    body: [
      "Alle regelendringer og prinsipielle beslutninger skal behandles i GeoTinget og protokollføres. Se § 2 for krav til gyldige vedtak.",
      "GeoTinget er Geotias lovgivende, kranglende og mytedannende forsamling.",
    ],
  },
  {
    paragraph: "§ 8",
    title: "Arkivplikten og Statsarkivet",
    body: [
      "Alle runder, resultater og merkbare hendelser skal registreres i det offisielle Statsarkivet.",
      "Historikken er hellig. Det som ikke er protokollført har ikke funnet sted.",
    ],
  },
  {
    paragraph: "§ 9",
    title: "Konespillet",
    body: [
      "Konespillet er et paraspill som registrerer konenes reaksjoner på geotisk aktivitet.",
      "6p - Sexnekt.",
      "5p - Utbrudd.",
      "4p - Kald skulder / silent treatment.",
      "3p - Sur kommentar.",
      "2p - Drepende blikk.",
      "1p - Himling.",
      "Konespillet reguleres ikke av GeoGrunnloven, men protokollføres med den alvor situasjonen fortjener.",
    ],
  },
];

const code = [
  "Vi resonnerer høyt, og alle tanker deles.",
  "Alle hint deles. Ingen informasjon holdes tilbake fra en medgeot.",
  "Vi konkurrerer, men vi lar aldri en geot falle utenfor.",
  "Om en geot foreslår et åpenbart feil sted blir han umiddelbart korrigert av de andre geotene. En geot får aldri dra til India uten å få klar beskjed!.",
  "Vi latterliggjør den som stikker bort fra flokken, og vi river ned den som hever seg over resten!",
  "En geot kan alltid gjenreise sin ære ved å argumentere godt og stikke hardt mot andre geoter.",
  "Man kan bli ekspert på et hvilket som helst felt. Førstemann til mølla. Men andre geoter kan ta opp kampen.",
  "Arkivfragment fra originalnotat: neplvenidppengeei og al.",
];

const lex = (
  term: string,
  definition: string,
  category: string,
  origin = "Statsarkivet",
  example = "Føres i protokollen ved behov.",
  comment = "Geotisk presisjon med passende høytid.",
): LexiconEntry => ({ term, definition, origin, example, comment, category });

const lexicon: LexiconEntry[] = [
  lex(
    "Geotia",
    "Riket, universet og statsapparatet som oppstod da geografi, vennskap og intern maktkamp ble institusjonalisert.",
    "Riket",
    "Grunnfortellingen",
    "Geotia krever protokoll før runden kan låses.",
    "Ikke bare en gruppe som spiller geografi. En sivilisasjon.",
  ),
  lex("Geot", "Statsborger, deltaker og medbærer av den geotiske byrde.", "Riket", "Geotia", "En sann geot deler hint før han feiler.", "Folket i Geotia er geoter."),
  lex("Geoter", "Folk: Geoter.", "Riket", "Statslæren", "Folkeregisteret viser syv geoter.", "Brukes om hele folket."),
  lex("Geotisme", "Nasjonalideologi: Geotisme.", "Riket", "Nasjonalideologien", "Geotismen krever at du sier tanken høyt.", "Statsideologi og sosial lim."),
  lex("SlowGeo", "Spillformen der geotene tipper et sted og rangeres etter avstand fra fasit.", "Spill", "1. januar", "SlowGeo i kveld, embetsverket er varslet.", "Grunnspillet og tidsregningen."),
  lex("Kattometeret", "Legger sammen antall kilometer man bommer med. Den med færrest kilometer vinner.", "Spill", "Kattometerlæren", "Kattometeret glemmer ikke.", "Ikke-deltakere får snittet av de tre dårligste."),
  lex("Konespillet", "Et paraspill som registrerer konenes reaksjoner på geotisk aktivitet.", "Spill", "GeoGrunnloven § 9", "Konespillet reguleres ikke av GeoGrunnloven.", "Protokollføres med den alvor situasjonen fortjener."),
  lex("GeoTinget", "Geotias lovgivende, kranglende og mytedannende forsamling.", "Institusjon", "15. januar", "Dette må til GeoTinget.", "Både parlament og sosialt trykkammer."),
  lex("GeoVAR", "Kontrollorganet som etterprøver tvilstilfeller, ære og mulige lovbrudd.", "Institusjon", "2. februar", "Send den til GeoVAR før stemningen kollapser.", "Høy symbolverdi, varierende saksbehandlingstid."),
  lex("GeoKodeksen", "Geotias moralske og sosiale normverk for deling, stikk og kollektiv sannhetssøk.", "Institusjon", "Tradisjonen", "GeoKodeksen sier at hintet skal deles.", "Rikets uskrevne lov som selvsagt er skrevet ned."),
  lex("GeoGrunnloven", "Konstitusjonen for SlowGeo og Geotia.", "Institusjon", "14. januar", "Endringer krever konsensus på GeoTinget.", "Lovtekst med både alvor og intern brodd."),
  lex("Statsarkivet", "Det nåværende registeret for Geotias spill, forslag, stemmer og annaler.", "Institusjon", "Appen", "Alle nye spilløkter føres i Statsarkivet.", "Historien finnes som inspirasjon, men aktive tabeller starter rent."),
  lex("Geosofi", "Høylytt tenkning om sted, tegn og mening.", "Riket", "Geopagos", "Geosofene la ut sin Geosofi hele dagen.", "Filosofi med mer kart og mer mistenksomhet."),
  lex("Geopagos", "Stedet der geosofene i det gamle Geotia stod og la ut sin Geosofi hele dagen.", "Riket", "Forhistorien", "Som i de gamle dager på Geopagos.", "Halvmytisk, helnyttig."),
  lex("Geotia City", "Geotias hovedstad og maktsentrum.", "Riket", "15. januar", "Geotia City ble grunnlagt samme dag som institusjonsiveren tok form.", "Symbolsk sentrum for all protokollføring."),
  lex("Politisk harakiri", "Når et parti påvirkes til å ødelegge egne muligheter, gjerne under MOSSAD-observasjon.", "Politikk", "MOSSAD", "Psykologisk påvirkning frembrakte politisk harakiri.", "Et effektivistisk ideal med mørk saksbehandling."),
  lex("Å ta en India", "En panisk avgjørelse i siste liten, som ender opp som en betydelig dårligere avgjørelse.", "Ord og uttrykk", "Klassisk feilslag", "Han tok en India og byttet kontinent med full selvtillit.", "Akutt varsel om kollektiv korrigering."),
  lex("Å ta en Sarajevo", "Være svært selvsikker, gå ekstremt høyt ut OG treffe blink.", "Ord og uttrykk", "Sarajevodagen", "Det var en ren Sarajevo.", "Heroisk, men farlig for ydmykheten."),
  lex("Å ta en El Tari", "En geot googler svaret og lurer Geotia.", "Ord og uttrykk", "El Tari Airport-hendelsen", "GeoVAR lukter El Tari.", "Moralsk tvilsom praksis."),
  lex("Gule skilter bak, hvite foran", "Gule skilter bak og hvite foran - UK.", "Kjennetegn", "Skiltologi"),
  lex("Stolper i betong", "Stolper i betong - Frankrike.", "Kjennetegn", "Stolpologi"),
  lex("Stolper i betong med hull", "Stolper i betong, med hull i - Polen/Romania.", "Kjennetegn", "Stolpologi"),
  lex("Polstrede lyktestolper", "Polstrede lyktestolper - Russland.", "Kjennetegn", "Lysmastlæren"),
  lex("Gule bilskilt", "Gule bilskilt - Nederland.", "Kjennetegn", "Skiltologi"),
  lex("Rennesteinen", "Rennesteinen i Brasil.", "Kjennetegn", "Veilæren"),
  lex("Gule midtstriper", "Gule midtstriper i Norge, USA, Brasil og kanskje hele latinamerika.", "Kjennetegn", "Veilæren"),
  lex("Argentina-stripe", "Argentina har både gul og hvit midtstripe, men ikke samtidig.", "Kjennetegn", "Veilæren"),
  lex("Gul sidekant på veien", "Gul stripe på sidene av veien - Sør-Afrika.", "Kjennetegn", "Veilæren"),
  lex("Amerikanske skilter på engelsk", "Amerikanske skilter på engelsk på Filippinene.", "Kjennetegn", "Skiltologi"),
  lex("De dyrker mais i Polen", "Landbrukstegn som peker mot Polen.", "Kjennetegn", "Referanselæren"),
  lex("Gule og svarte skiltstolper", "Gule og svarte skiltstolper - Botswana?", "Kjennetegn", "Skiltologi"),
  lex("Grønne kontante pilskilt", "Grønne kontante pilskilt i USA, bare i USA.", "Kjennetegn", "Skiltologi"),
  lex("Tykke gule striplete veiskuldre", "Irland har tykke gule striplete veiskuldre.", "Kjennetegn", "Veilæren"),
  lex("Svette trær", "Australia har svette trær.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Furuskog ispedd palmer og myr", "Florida har furuskog ispedd palmer og myr.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Ser ut som USA, men noe er feil", "Hvis det er USA men noe er feil er det Canada.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Brasil? Det er nordøst", "Hvis det er Brasil er det som oftes nord-øst i Brasil.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Shabby men rart", "Hvis det er shabby men rart er det ofte Japan. Med sammentrykte biler.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Kyrilliske bokstaver", "Mongolia har kyrilliske bokstaver.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Flagg i nordlige Sør-Amerika", "Husk at flaggene til de nordligste landene i Sør-Amerika ser nesten helt like ut.", "Indianerkjennetegn", "Indianerkjennetegn"),
  lex("Damer på sykler", "Damer på sykler er nederlandske.", "Referanser", "Referanselæren"),
  lex("Nederland vs. Russland", "Nederland kan se ut som Russland hvis det er overskyet.", "Referanser", "Referanselæren"),
  lex("Gule svenske blokker", "Gule svenske blokker er mest sannsynlig Malmö 😄.", "Referanser", "Referanselæren"),
  lex("Kulehull i murbygninger", "Kulehull i murbygninger betyr mest sannsynlig Sarajevo!.", "Referanser", "Referanselæren"),
  lex("Langt inni granskauen øst i Russland", "Hvis man tenker at det langt inni granskauen øst i Russland er det somoftest vest for Moskva.", "Referanser", "Referanselæren"),
  lex("Vestlandsfjord + Sørlandet", "Ser det litt ut som en vestlandsfjord kombinert med sørlandet er det Nord-Norge.", "Referanser", "Referanselæren"),
  lex("Shabby østkystaktige hus", "Er det shabby østkystaktige hus er det mest sannsynlig Detroit.", "Referanser", "Referanselæren"),
  lex("New Zealand vs. Irland", "Tror du det er New Zealand, kan det like godt være Irland. Og omvendt.", "Referanser", "Referanselæren"),
  lex("Kina og Taiwan", "Kina har mange elver, det har også Taiwan.", "Referanser", "Referanselæren"),
  lex("Brungulegrønne floder", "Brungulegrønne floder finnes over hele Asia.", "Referanser", "Referanselæren"),
  lex("Blå gatenavnskilt", "Tyskland har blå gatenavnskilt, men det har også Østerrike.", "Referanser", "Referanselæren"),
  lex("Langt inni Amazonas", "Langt inni Amazonas ligner det på det vi tenker Victoriasjøen ser ut som.", "Referanser", "Referanselæren"),
  lex("Kamtsjatkahalvøyen", "På Kamtsjatkahalvøyen er det en landsby som ser ut som de lever på 1800-tallet og hvis man snur seg til venstre kan man se et syyykt kult vulkanfjell.", "Referanser", "Referanselæren"),
  lex("Petit verdot", "Petit verdot er en drue, ikke er sted i Frankrike.", "Advarsel", "Navnefadese", "GeoVAR avviser Petit verdot som geografisk svar.", "Hard justis mot frukt og bær."),
  lex("Polen med fine hager", "Ser det ut som Polen, men hagene er fine så er det Litauen eller Estland.", "Referanser", "Referanselæren"),
  lex("Det går alltid oppover", "Det går alltid oppover i Peru.", "Referanser", "Referanselæren"),
  lex("Er det utsikt", "Er det utsikt er det Bolivia.", "Referanser", "Referanselæren"),
  lex("Slovakia aldri flatt", "I Slovakia er det aldri flatt mer enn 500m om gangen.", "Referanser", "Referanselæren"),
  lex("Ser ut som Sør-Afrika med afrikanske navn", "Om det ser ut som Sør-Afrika, men har afrikanske navn så er det Eswatini.", "Referanser", "Referanselæren"),
  lex("Bokstaver som elektrosjokk", "Om bokstavene ser ut som elektrosjokk så er det Polen.", "Referanser", "Referanselæren"),
  lex("Ingen støpekanter + gul stripe + dego", "Om det ikke er støpekanter og det er gul stripe, og det er en dego langs veien, så er det Mexico.", "Referanser", "Referanselæren"),
];

const calendar: CalendarEvent[] = [
  {
    date: "1. januar",
    name: "SlowGeos fødselsdag",
    category: "Historisk",
    description: "Dagen geotene virkelig kom til liv. SlowGeo ble til.",
    significance: "Fundamental. Geotias opprinnelse.",
  },
  {
    date: "14. januar",
    name: "Pinot Noir-dagen",
    category: "Historisk",
    description: "Dagen GeoGrunnloven ble befestet.",
    significance: "Pinot Noir er en drue, ikke Frankrike.",
  },
  {
    date: "15. januar",
    name: "GeoTinget grunnlagt",
    category: "Institusjonell",
    description: "GeoTinget ble opprettet som lovgivende forsamling.",
    significance: "Lovgivningens dag.",
  },
  {
    date: "15. januar",
    name: "Geotia City grunnlagt",
    category: "Historisk",
    description: "Geotias hovedstad og maktsentrum ble etablert.",
    significance: "Byens fødsel.",
  },
  {
    date: "16. januar",
    name: "Geokrati-dagen",
    category: "Politisk",
    description: "Alle geoter ble representert i et parti. Det fullt partipolitiske Geotia ble til.",
    significance: "Demokratiets dag i Geotia.",
  },
  {
    date: "21. januar",
    name: "Den første terrorbombingen",
    category: "Traumatisk",
    description: "Dagen da SS sprengte partikontoret til PKK. Geotias møte med intern terror.",
    significance: "Politisk dramatikk på høyeste nivå.",
  },
  {
    date: "31. januar",
    name: "Første GeoTing",
    category: "Institusjonell",
    description: "Det første offisielle møtet i GeoTinget ble avholdt.",
    significance: "Start på parlamentarisk tradisjon.",
  },
  {
    date: "2. februar",
    name: "Første GeoVAR",
    category: "Institusjonell",
    description: "Den første bruken av GeoVAR - kontrollorganet satt i spill.",
    significance: "Rettsstatens fødsel i Geotia.",
  },
  {
    date: "6. februar",
    name: "Botswana-dagen",
    category: "Historisk",
    description: "Adling av Ingebjørg. Geotisk adel og seremoni ble virkelighet.",
    significance: "Tegn på at geotisk adel finnes.",
  },
  {
    date: "9. februar",
    name: "Byvandringsdagen",
    category: "Episk",
    description: "Dagen geotene vandret hvileløst rundt i Wien for å finne svaret. Geotisk eksodus.",
    significance: "Et slags eksodusmotiv i geotisk tradisjon.",
  },
  {
    date: "24. mai",
    name: "Antiklimaksdagen",
    category: "Tragikomisk",
    description: "Progreso vs. Nuevo Progreso + El Tari Airport. Geotisk tragedie i lavskalaformat.",
    significance: "Det lavskala antiklimakets store dag.",
  },
  {
    date: "26. mai",
    name: "Sarajevodagen",
    category: "Traumatisk/Heroisk",
    description: "Dagen geo nesten døde. En heroisk, traumatisk og nesten apokalyptisk fortelling.",
    significance: "Fundamental geotisk mytedag.",
  },
];

const episodes: ArchiveEpisode[] = [
  {
    id: "sarajevodagen",
    title: "Sarajevodagen",
    date: "26. mai",
    category: "Traumatisk/Heroisk",
    summary: "Dagen geo nesten døde, men i stedet ble en læresetning om selvtillit, kulehull og kollektiv redning.",
    rememberedFor: [
      "Å ta en Sarajevo: høyt ut, hånet, kvalmende sikker og blink.",
      "Balkan-tegn ble mytologisk materiale, ikke bare kartdata.",
      "Flokken lærte at ekstrem selvtillit kan være både gift og nådegave.",
    ],
    lesson: "Når noen ser Sarajevo i murpussen, skal de hånes, men ikke nødvendigvis ignoreres.",
    relatedTerms: ["Å ta en Sarajevo", "Kulehull i murbygninger", "GeoKodeksen"],
  },
  {
    id: "byvandringsdagen",
    title: "Byvandringsdagen",
    date: "9. februar",
    category: "Episk",
    summary: "Dagen geotene vandret hvileløst rundt i Wien for å finne svaret og gjorde leting til eksodusmotiv.",
    rememberedFor: [
      "Fysisk uro ble geotisk metode.",
      "Wien ble mer enn fasit; byen ble en prøvelse.",
      "Runden beviste at kart ikke alltid er nok når kroppen krever ritual.",
    ],
    lesson: "Noen ganger må man gå seg vill på ordentlig for å forstå hvor feil man nesten var.",
    relatedTerms: ["Byvandringsdagen", "Wien", "Eksodus"],
  },
  {
    id: "pinot-noir",
    title: "Pinot Noir-dagen",
    date: "14. januar",
    category: "Konstitusjonell",
    summary: "Dagen GeoGrunnloven ble befestet gjennom den evige sannheten: Pinot Noir er en drue, ikke Frankrike.",
    rememberedFor: [
      "Frukt, bær og vin ble rettslig farlige kategorier.",
      "GeoVARs ånd fikk tidlig næring.",
      "Navnefadese ble til lovstoff.",
    ],
    lesson: "Et geografisk navn må fortsatt være et sted. Druer får null og varig mistanke.",
    relatedTerms: ["Petit verdot", "Fruktistan-Sympatisør", "GeoVAR"],
  },
  {
    id: "el-tari",
    title: "El Tari-episoden",
    date: "Dato ukjent",
    category: "Mistenkelig presisjon",
    summary: "Episoden som ga Geotia et språk for for presise svar uten synlig resonnement.",
    rememberedFor: [
      "Å ta en El Tari ble arkivets navn på mistenkelig presisjon.",
      "Skjermdeling og sosial kulde ble mulige renselsesmidler.",
      "Riket lærte at rett svar også kan kreve forklaring.",
    ],
    lesson: "Presisjon uten resonnement er ikke bare seier. Det er bevismateriale.",
    relatedTerms: ["Å ta en El Tari", "GeoVAR", "El Tari-Klassen"],
  },
  {
    id: "botswana-dagen",
    title: "Botswana-dagen",
    date: "6. februar",
    category: "Adel og seremoni",
    summary: "Dagen adling av Ingebjørg gjorde geotisk adel mulig, og dermed også nødvendig å føre med alvor.",
    rememberedFor: [
      "Geotia fikk adel som sosialt faktum.",
      "Seremonien viste at overbygningen kan være rik uten å gjøre motoren tung.",
      "Riket fikk et glimt av orden før Ordenen ble egen institusjon.",
    ],
    lesson: "Når fellesskapet lager en seremoni, må arkivet late som det alltid var en institusjon.",
    relatedTerms: ["Botswana-dagen", "Den Geotiske Orden", "Geotisk adel"],
  },
];

const geotingCases: GeotingCase[] = [
  {
    date: "15. januar",
    caseNumber: "GT-001",
    caseName: "Opprettelse av GeoTinget",
    proposal: "GeoTinget herved opprettet som Geotias lovgivende forsamling.",
    proposedBy: "Alle geoter",
    decision: "Vedtatt",
    votes: "7/7",
    status: "Vedtatt",
    comment: "Grunnleggende institusjonsvedtak.",
  },
  {
    date: "15. januar",
    caseNumber: "GT-002",
    caseName: "Geotia City grunnlagt",
    proposal: "Geotia City vedtatt som Geotias offisielle hovedstad.",
    proposedBy: "Alle geoter",
    decision: "Vedtatt",
    votes: "7/7",
    status: "Vedtatt",
    comment: "Symbolsk vedtak av høy historisk verdi.",
  },
  {
    date: "16. januar",
    caseNumber: "GT-003",
    caseName: "Geokrati-dagen",
    proposal: "Alle geoter representeres i eget politisk parti.",
    proposedBy: "Alle geoter",
    decision: "Vedtatt",
    votes: "7/7",
    status: "Vedtatt",
    comment: "Dagen alle 7 partier ble til. Geokrati-dagen.",
  },
  {
    date: "31. januar",
    caseNumber: "GT-004",
    caseName: "Første ordinære GeoTing",
    proposal: "Første formelle møte i GeoTinget avholdt.",
    proposedBy: "GeoTinget",
    decision: "Avholdt",
    votes: "7/7",
    status: "Historisk",
    comment: "Starten på en geotisk parlamentarisk tradisjon.",
  },
  {
    date: "Dato ukjent",
    caseNumber: "GT-005",
    caseName: "Forsinket feiring - SlowGeos fødselsdag",
    proposal: "Forsinket feiring i forbindelse med SlowGeos fødselsdag.",
    proposedBy: "Innkommet forslag",
    decision: "-",
    votes: "-",
    status: "Under behandling",
    comment: "Ikke endelig behandlet.",
  },
  {
    date: "Dato ukjent",
    caseNumber: "GT-006",
    caseName: "Komite for grunnlovsdagen",
    proposal: "Opprette komite for planlegging av grunnlovsdagen til Geotia.",
    proposedBy: "Innkommet forslag",
    decision: "-",
    votes: "-",
    status: "Under behandling",
    comment: "Ikke endelig behandlet.",
  },
  {
    date: "21. januar",
    caseNumber: "GT-007",
    caseName: "Den første terrorbombingen",
    proposal: "Sak etter at SS sprengte partikontoret til PKK.",
    proposedBy: "PKK / SS",
    decision: "Registrert",
    votes: "-",
    status: "Historisk",
    comment: "Første terrorangrep i Geotia. Dypt symbolsatt.",
  },
  {
    date: "Løpende",
    caseNumber: "GT-008",
    caseName: "Kattometerets integritet",
    proposal:
      "Ikke-deltakelse skal gi tellende km lik snittet av de tre dårligste gyldige resultatene.",
    proposedBy: "Statsarkivet",
    decision: "Innført i appen",
    votes: "Embetsvedtak",
    status: "Iverksatt",
    comment: "Passiv geografisk desertering er ikke lenger et smutthull.",
  },
];

const oldSlowGeo: OldSlowGeoRecord[] = [
  { player: "Alf Kåre", points: 84, pointRounds: 18, kattometer: 12104, kattometerRounds: 18 },
  { player: "Fredrik", points: 106, pointRounds: 19, kattometer: 10592, kattometerRounds: 19 },
  { player: "Jørgen", points: 17, pointRounds: 3, kattometer: 629, kattometerRounds: 3 },
  { player: "Sverre", points: 41, pointRounds: 10, kattometer: 8227, kattometerRounds: 11 },
  { player: "Steinar", points: 77, pointRounds: 18, kattometer: 12909, kattometerRounds: 18 },
  { player: "Vegard", points: 87, pointRounds: 19, kattometer: 13720, kattometerRounds: 18 },
  { player: "Glenn Ruben", points: 83, pointRounds: 18, kattometer: 13666, kattometerRounds: 18 },
];

const knowledgeGroups: KnowledgeGroup[] = [
  {
    title: "Kjennetegn",
    description: "Rikets praktiske tegnlære, med samme sikkerhet som en god magefølelse.",
    items: [
      "Gule skilter bak og hvite foran - UK",
      "Stolper i betong - Frankrike",
      "Stolper i betong, med hull i - Polen/Romania",
      "Polstrede lyktestolper - Russland",
      "Gule bilskilt - Nederland",
      "Rennesteinen i Brasil",
      "Gule midtstriper i Norge, USA, Brasil og kanskje hele latinamerika",
      "Argentina har både gul og hvit midtstripe, men ikke samtidig",
      "Gul stripe på sidene av veien - Sør-Afrika",
      "Amerikanske skilter på engelsk på Filippinene",
      "De dyrker mais i Polen",
      "Gule og svarte skiltstolper - Botswana?",
      "Grønne kontante pilskilt i USA, bare i USA",
    ],
  },
  {
    title: "Indianerkjennetegn",
    description: "Overleverte observasjoner fra den intuitive skolen.",
    items: [
      "Australia har svette trær",
      "Florida har furuskog ispedd palmer og myr.",
      "Hvis det er USA men noe er feil er det Canada.",
      "Hvis det er Brasil er det som oftes nord-øst i Brasil.",
      "Hvis det er shabby men rart er det ofte Japan. Med sammentrykte biler.",
      "Mongolia har kyrilliske bokstaver.",
      "Husk at flaggene til de nordligste landene i Sør-Amerika ser nesten helt like ut.",
    ],
  },
  {
    title: "Referanser",
    description: "Små, farlige setninger som ofte leder rett nok til å skape selvtillit.",
    items: [
      "Damer på sykler er nederlandske",
      "Nederland kan se ut som Russland hvis det er overskyet.",
      "Gule svenske blokker er mest sannsynlig Malmö 😄",
      "Kulehull i murbygninger betyr mest sannsynlig Sarajevo!",
      "Hvis man tenker at det langt inni granskauen øst i Russland er det somoftest vest for Moskva.",
      "Ser det litt ut som en vestlandsfjord kombinert med sørlandet er det Nord-Norge.",
      "Er det shabby østkystaktige hus er det mest sannsynlig Detroit.",
      "Tror du det er New Zealand, kan det like godt være Irland. Og omvendt",
      "Kina har mange elver, det har også Taiwan.",
      "Brungulegrønne floder finnes over hele Asia",
      "Tyskland har blå gatenavnskilt, men det har også Østerrike.",
      "Langt inni Amazonas ligner det på det vi tenker Victoriasjøen ser ut som.",
      "På Kamtsjatkahalvøyen er det en landsby som ser ut som de lever på 1800-tallet og hvis man snur seg til venstre kan man se et syyykt kult vulkanfjell.",
      "Petit verdot er en drue, ikke er sted i Frankrike",
      "Ser det ut som Polen, men hagene er fine så er det Litauen eller Estland",
      "Det går alltid oppover i Peru",
      "Er det utsikt er det Bolivia",
      "I Slovakia er det aldri flatt mer enn 500m om gangen",
      "Om det ser ut som Sør-Afrika, men har afrikanske navn så er det Eswatini.",
      "Om bokstavene ser ut som elektrosjokk så er det Polen.",
      "Om det ikke er støpekanter og det er gul stripe, og det er en dego langs veien, så er det Mexico",
      "Irland har tykke gule striplete veiskuldre",
    ],
  },
];

const konespillet: KonespillRule[] = [
  { points: 6, reaction: "sexnekt" },
  { points: 5, reaction: "utbrudd" },
  { points: 4, reaction: "kald skulder/silent treatment" },
  { points: 3, reaction: "sur kommentar" },
  { points: 2, reaction: "drepende blikk" },
  { points: 1, reaction: "himling" },
];

const canon: CanonSection[] = [
  {
    title: "Geotia",
    eyebrow: "Riksidentitet",
    body: [
      "Geotia",
      "Folk: Geoter",
      "Nasjonalideologi: Geotisme",
      "Geosofene i det gamle Geotia stod på Geopagos og la ut sin Geosofi hele dagen.",
      "Originalnotatet markerte bilder med ￼; i appen vises disse som partikortene og partioversikten fra kildemappen.",
    ],
  },
  {
    title: "SAKER FOR GEOTINGET",
    eyebrow: "Saksliste",
    body: [
      "Forsinket feiring i forbindelse med SlowGeos fødselsdag.",
      "Opprette komité for planlegging av grunnlovsdagen til Geotia.",
      "GeoTinget er Geotias lovgivende, kranglende og mytedannende forsamling.",
    ],
  },
  {
    title: "GeoKodeksen",
    eyebrow: "Moralsk protokoll",
    body: [
      "Vi resonnerer høyt, og alle tanker deles",
      "Alle hint deles. Ingen informasjon holdes tilbake fra en medgeot.",
      "Vi konkurrerer, men vi lar aldri en geot falle utenfor",
      "Om en geot foreslår et åpenbart feil sted blir han umiddelbart korrigert av de andre geotene. En geot får aldri dra til India uten å få klar beskjed!.",
      "Vi latterliggjør den som stikker bort fra flokken, og vi river ned den som hever seg over resten!",
      "En geot kan alltid gjenreise sin ære ved å argumentere godt og stikke hardt mot andre geoter",
      "Man kan bli ekspert på et hvilket som helst felt. Førstemann til mølla. Men andre geoter kan ta opp kampen.neplvenidppengeei og al",
    ],
  },
  {
    title: "GEOGRUNNLOVEN",
    eyebrow: "Konstitusjonen",
    body: [
      "Tidsrom for frist: 10:00 - 23:00",
      "Hvert spill må ha minst 1 times frist",
      "Fristen rundes opp til nærmeste kvarter",
      "Fristen kan forkortes om alle geoter har svart (7/7).",
      "Det er bildets ankomst som avslutter runden, ikke fristen. Bildet kan ikke komme før fristen, men et svar kan komme etter fristen så lenge bildet ikke er sendt.",
      "Minimum antall deltakere: 5 geoter",
      "Delt plassering gir poengsummen til den delte plasseringen.",
      "Endringer i GeoGrunnloven kan kun skje ved konsensus på GeoTinget (7/7). Alle Geoter må ha avgitt stemme for at avstemningen skal være gyldig. Gjør din plikt, krev din rett Geoter!",
      "Mindre lovendringer kan vedtas ved rent flertall (4/7) blant geomentarikerne på GeoTinget.",
    ],
  },
  {
    title: "Avgitt svar",
    eyebrow: "Svarlæren",
    body: [
      "Siste svar gjelder",
      "Alle svar må ha utgangspunkt i et konkret sted, med valgfrie presiseringer som kilometer og himmelretninger.",
      "Sverre har unntak fra denne regelen",
      "Om man kun svarer et land/en stat, uten videre presiseringer, blir svaret automatisk midt i landet/staten.",
      "Bare geografiske steder på jorden kan gi poeng. Frukt, bær, grønnsaker eller alle andre ting gir 0 poeng.",
      "Alle land deles i tre både vertikalt og horisontalt (sør-midt-nord og vest-midt-øst). Om noen bare sier for eksempel «nord» blir det det målt fra midten av den øvre tredel.",
      "Himmelretninger er et område, ikke et punkt.",
    ],
  },
  {
    title: "Poengfordeling",
    eyebrow: "Rang og ære",
    body: [
      "1. 7p",
      "2. 6p",
      "3. 5p",
      "4. 4p",
      "5. 3p",
      "6. 2p",
      "7. 1p",
      "Ikke deltatt/ikke godkjent svar: 0p",
    ],
  },
  {
    title: "Kattometeret",
    eyebrow: "Kilometerdommen",
    body: [
      "Legger sammen antall kilometer man bommer med. Den med færrest kilometer vinner.",
      "Kilometerene for den/de som ikke deltar er gjennomsnittet av de tre dårligste.",
    ],
  },
  {
    title: "Merkedager",
    eyebrow: "Geotisk kalender",
    body: [
      "26. mai - Sarajevodagen: Dagen geo nesten døde",
      "1. januar - SlowGeos fødselsdag og dagen geotene virkelig kom til liv",
      "14. januar - Pinot Noir-dagen: dagen GeoGrunnloven ble befestet",
      "15. januar - GeoTinget ble opprettet",
      "15. januar - Geotia City grunnlagt",
      "16. januar - Geokrati-dagen - Alle geoter representert i et parti",
      "21. januar - Den første terrorbombingen i Geotia. Dagen da SS sprengte partikontoret til PKK.",
      "31. januar - første GeoTing",
      "2. februar - første GeoVAR",
      "6. februar - Botswana-dagen med adling av Ingebjørg.",
      "9. februar - Byvandringsdagen - dagen geotene vandret hvileløst rundt i Wien for å finne svaret.",
      "24. mai - Antiklimaksdagen - Progreso vs. Nuevo Progreso + El Tari Airport",
    ],
  },
  {
    title: "Ord og uttrykk",
    eyebrow: "Språket",
    body: [
      "Å ta en India: En panisk avgjørelse i siste liten, som ender opp som en betydelig dårligere avgjørelse.",
      "Å ta en Sarajevo: Være svært selvsikker, gå ekstremt høyt ut OG treffe blink",
      "Å ta en El Tari: En geot googler svaret og lurer Geotia",
    ],
  },
  {
    title: "Kjennetegn",
    eyebrow: "Tegnlære",
    body: knowledgeGroups[0].items,
  },
  {
    title: "Indianerkjennetegn",
    eyebrow: "Intuitiv tegnlære",
    body: knowledgeGroups[1].items,
  },
  {
    title: "Referanser",
    eyebrow: "Muntlig kartografi",
    body: knowledgeGroups[2].items,
  },
  {
    title: "GEOTINGET",
    eyebrow: "Partienes fulltekst",
    body: [
      "Sannhetssøkende Sentrumsekstremister (SS) - Obergruppenführer Alf Kåre Dalsbø",
      ...parties[0].manifesto!,
      "MOTTO: Kontrollere for å fornye og bevare!",
      "IDEOLOGI: Machtsteuerunglebensraum (Kontrollisme)",
      ...parties[0].doctrine!,
      "Det Progressive KrangleKalifat - Sultan og KrangleKalif Steinar Lofnes av PKK",
      ...parties[1].manifesto!,
      "Motto: Krangling for kranglingens skyld!",
      "Ideologi: Konfliktisme",
      "PoengLiberales organisasjon (PLO)- Jørgen Deem / Pepsi Sjeik Nub Barack av PLO",
      ...parties[2].manifesto!,
      "Ingen Reell Alternering (IRA) - Vegard Lofnes",
      ...parties[3].manifesto!,
      "Motto: Beskytt grunnloven ved døden; praesidio constitutionis a morte",
      "MOSSAD: Må Orke Spesielle, Slitsomme, Alternative Derivasjoner - Fredrik Skoglund",
      ...parties[4].manifesto!,
      "Cisterienserindianerpartiet (CIP) - Cisterienserindianer Sverre Skilbreid",
      ...parties[5].manifesto!,
      "Pølser og whiskey-partiet (PWP) - Ruben Furu-Borgen",
      ...parties[6].manifesto!,
      "PLO | IRA | SS | PKK | PWP | CIP | MOSSAD",
    ],
  },
  {
    title: "KONESPILLET",
    eyebrow: "Paraspill",
    body: [
      "6 poeng for sexnekt",
      "5 poeng for utbrudd",
      "4 poeng for kald skulder/silent treatment",
      "3 poeng for sur kommentar",
      "2 poeng for drepende blikk",
      "1 poeng for himling",
    ],
  },
];

export const archive: ArchiveData = {
  constitution,
  code,
  lexicon,
  calendar,
  episodes,
  geotingCases,
  oldSlowGeo,
  geosophy: [
    "Den som vet hvor han er, vet ikke nødvendigvis hvor andre er.",
    "Motoren enkel. Overbygningen rik.",
    "Staten må ikke bli så byråkratisk at ingen møter opp til embetsverket.",
    "En geot får aldri dra til India uten å få klar beskjed.",
    "Når veien er uklar, følger vi kompasset i hjertet og tabellen i statsarkivet.",
    "Kattometeret glemmer ikke, men det fører protokoll med verdighet.",
  ],
  canon,
  knowledgeGroups,
  konespillet,
};

export const initialState: AppState = {
  players,
  playerProfiles: [],
  parties,
  games,
  archive,
  rounds: [],
  gameSessions: [],
  geotingProposals: [],
  geoterIndexAdjustments: [],
  geoticOrderAssessments: [],
  geoticOrderPromotionCases: [],
};
