import { randomUUID } from "node:crypto";

import { isSafeSlowGeoAttribution } from "@/lib/slowgeo-share";
import type { SlowGeoChallenge, SlowGeoDifficulty } from "@/lib/types";

type StreetViewCandidate = {
  id: string;
  label: string;
  country: string;
  continent: string;
  lat: number;
  lon: number;
  heading: number;
  pitch?: number;
  fov?: number;
  difficulty: SlowGeoDifficulty;
  theme: string;
  signature: string;
  tags: string[];
};

type StreetViewMetadataResponse = {
  status: string;
  pano_id?: string;
  location?: {
    lat?: number;
    lng?: number;
  };
  date?: string;
  copyright?: string;
  error_message?: string;
};

const slowGeoPoolExhaustedMessage =
  "Alle kuraterte SlowGeo-bilder er brukt. Legg til nye kandidater før neste runde.";

export const slowGeoCandidates: StreetViewCandidate[] = [
  {
    id: "sarajevo-bascarsija",
    label: "Baščaršija, Sarajevo",
    country: "Bosnia-Hercegovina",
    continent: "Europa",
    lat: 43.8594,
    lon: 18.4312,
    heading: 88,
    pitch: 2,
    fov: 92,
    difficulty: "middels",
    theme: "Balkan og kulehull-lære",
    signature: "Sarajevodagen lurer alltid i murpussen.",
    tags: ["sarajevo", "europa", "by"],
  },
  {
    id: "tromso-bridge",
    label: "Tromsøbrua, Tromsø",
    country: "Norge",
    continent: "Europa",
    lat: 69.6534,
    lon: 18.975,
    heading: 64,
    pitch: 1,
    fov: 90,
    difficulty: "lett",
    theme: "nordlysstat og norsk veifølelse",
    signature: "Fjell, vann og nordlig infrastruktur uten skam.",
    tags: ["norge", "nord", "bro"],
  },
  {
    id: "wellington-cable-car",
    label: "Cable Car Lane, Wellington",
    country: "New Zealand",
    continent: "Oseania",
    lat: -41.2855,
    lon: 174.7749,
    heading: 340,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "øystat med britisk etterklang",
    signature: "New Zealand kan alltid late som det er Irland, og omvendt.",
    tags: ["oseania", "øy", "by"],
  },
  {
    id: "montevideo-rambla",
    label: "Rambla República del Perú, Montevideo",
    country: "Uruguay",
    continent: "Sør-Amerika",
    lat: -34.9138,
    lon: -56.1461,
    heading: 110,
    pitch: 0,
    fov: 92,
    difficulty: "hard",
    theme: "søramerikansk kystro",
    signature: "Ramblaen smiler som om Buenos Aires ikke står i rommet.",
    tags: ["sor-amerika", "kyst", "by"],
  },
  {
    id: "riga-old-town",
    label: "Kaļķu iela, Riga",
    country: "Latvia",
    continent: "Europa",
    lat: 56.9496,
    lon: 24.109,
    heading: 215,
    pitch: 2,
    fov: 86,
    difficulty: "middels",
    theme: "baltisk gammelby",
    signature: "Nok Europa til at noen blir for selvsikre.",
    tags: ["baltikum", "europa", "by"],
  },
  {
    id: "valparaiso-cerro-alegre",
    label: "Cerro Alegre, Valparaíso",
    country: "Chile",
    continent: "Sør-Amerika",
    lat: -33.0399,
    lon: -71.6282,
    heading: 52,
    pitch: -4,
    fov: 90,
    difficulty: "hard",
    theme: "bratt fargekaos ved Stillehavet",
    signature: "Alt går oppover, men det er ikke Peru denne gangen.",
    tags: ["chile", "bratt", "kyst"],
  },
  {
    id: "tbilisi-rustaveli",
    label: "Rustaveli Avenue, Tbilisi",
    country: "Georgia",
    continent: "Asia",
    lat: 41.7021,
    lon: 44.793,
    heading: 101,
    pitch: 1,
    fov: 90,
    difficulty: "hard",
    theme: "Kaukasus mellom Europa og Asia",
    signature: "En perfekt arena for kontinentforvirring med høy selvtillit.",
    tags: ["kaukasus", "asia", "by"],
  },
  {
    id: "cape-town-bo-kaap",
    label: "Bo-Kaap, Cape Town",
    country: "Sør-Afrika",
    continent: "Afrika",
    lat: -33.9217,
    lon: 18.4156,
    heading: 148,
    pitch: 3,
    fov: 84,
    difficulty: "middels",
    theme: "fargerik sørspiss",
    signature: "Sør-Afrika når paletten bestemmer seg for å hjelpe.",
    tags: ["afrika", "sor-afrika", "farger"],
  },
  {
    id: "vilnius-pilies",
    label: "Pilies gatvė, Vilnius",
    country: "Litauen",
    continent: "Europa",
    lat: 54.6825,
    lon: 25.2891,
    heading: 6,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "litauisk hageorden",
    signature: "Polen-følelse med litt for pene kanter.",
    tags: ["litauen", "baltikum", "by"],
  },
  {
    id: "la-paz-mirador",
    label: "Mirador Killi Killi, La Paz",
    country: "Bolivia",
    continent: "Sør-Amerika",
    lat: -16.4938,
    lon: -68.1193,
    heading: 247,
    pitch: -7,
    fov: 94,
    difficulty: "lett",
    theme: "høyde, utsikt og geotisk svimmelhet",
    signature: "Er det utsikt, begynner Bolivia å rope.",
    tags: ["bolivia", "hoyde", "utsikt"],
  },
  {
    id: "seoul-bukchon",
    label: "Bukchon Hanok Village, Seoul",
    country: "Sør-Korea",
    continent: "Asia",
    lat: 37.5826,
    lon: 126.9839,
    heading: 136,
    pitch: 1,
    fov: 84,
    difficulty: "middels",
    theme: "østasiatisk presisjon og taklinjer",
    signature: "For ordentlig til å være en panikkteori, farlig nok likevel.",
    tags: ["asia", "sor-korea", "by"],
  },
  {
    id: "marrakesh-koutoubia",
    label: "Koutoubia, Marrakesh",
    country: "Marokko",
    continent: "Afrika",
    lat: 31.6242,
    lon: -7.9936,
    heading: 28,
    pitch: 2,
    fov: 88,
    difficulty: "middels",
    theme: "nordafrikansk varme",
    signature: "Sandfarget autoritet med minaret i sidesynet.",
    tags: ["afrika", "marokko", "by"],
  },
  {
    id: "dakar-plateau",
    label: "Plateau, Dakar",
    country: "Senegal",
    continent: "Afrika",
    lat: 14.6685,
    lon: -17.4359,
    heading: 78,
    pitch: 1,
    fov: 90,
    difficulty: "hard",
    theme: "vestafrikansk bylesning",
    signature: "Når Afrika ikke vil være det første geoten tør å si høyt.",
    tags: ["afrika", "senegal", "by"],
  },
  {
    id: "ghent-canal",
    label: "Graslei, Gent",
    country: "Belgia",
    continent: "Europa",
    lat: 51.0543,
    lon: 3.7206,
    heading: 250,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "kanaler, tegl og lavlandsforvirring",
    signature: "Nederlandsk selvtillit kan her bli belgisk korreksjon.",
    tags: ["europa", "belgia", "kanal"],
  },
  {
    id: "sapporo-odori",
    label: "Odori Park, Sapporo",
    country: "Japan",
    continent: "Asia",
    lat: 43.0606,
    lon: 141.3538,
    heading: 96,
    pitch: 0,
    fov: 86,
    difficulty: "hard",
    theme: "Japan, men ikke Tokyo-refleks",
    signature: "Shabby, ryddig og rart nok til å forstyrre alle.",
    tags: ["asia", "japan", "by"],
  },
  {
    id: "porto-ribeira",
    label: "Ribeira, Porto",
    country: "Portugal",
    continent: "Europa",
    lat: 41.1406,
    lon: -8.611,
    heading: 64,
    pitch: 1,
    fov: 88,
    difficulty: "middels",
    theme: "iberisk skråning og fliser",
    signature: "Ikke alle varme vegger er Spania.",
    tags: ["europa", "portugal", "kyst"],
  },
  {
    id: "cusco-san-blas",
    label: "San Blas, Cusco",
    country: "Peru",
    continent: "Sør-Amerika",
    lat: -13.5153,
    lon: -71.9763,
    heading: 192,
    pitch: -2,
    fov: 90,
    difficulty: "middels",
    theme: "andesby og oppoverlov",
    signature: "Det går alltid oppover i Peru, særlig i argumentasjonen.",
    tags: ["sor-amerika", "peru", "hoyde"],
  },
  {
    id: "tallinn-old-town",
    label: "Viru Gate, Tallinn",
    country: "Estland",
    continent: "Europa",
    lat: 59.4369,
    lon: 24.7504,
    heading: 310,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "baltisk middelaldermaskering",
    signature: "For pen til Polen, for farlig til at PLO får rett alene.",
    tags: ["baltikum", "estland", "by"],
  },
  {
    id: "kingston-waterfront",
    label: "Kingston Waterfront",
    country: "Jamaica",
    continent: "Nord-Amerika",
    lat: 17.9655,
    lon: -76.7936,
    heading: 135,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "karibisk kyst uten trygg autopilot",
    signature: "Når palmer ikke lenger betyr at noen egentlig vet noe.",
    tags: ["karibia", "jamaica", "kyst"],
  },
  {
    id: "bergen-bryggen",
    label: "Bryggen, Bergen",
    country: "Norge",
    continent: "Europa",
    lat: 60.3971,
    lon: 5.3245,
    heading: 38,
    pitch: 1,
    fov: 86,
    difficulty: "lett",
    theme: "vestlandsk treverk og regntrussel",
    signature: "Alt ser norsk ut, men noen kommer likevel til å rope Danmark.",
    tags: ["norge", "europa", "brygge"],
  },
  {
    id: "copenhagen-nyhavn",
    label: "Nyhavn, København",
    country: "Danmark",
    continent: "Europa",
    lat: 55.6798,
    lon: 12.591,
    heading: 104,
    pitch: 0,
    fov: 88,
    difficulty: "lett",
    theme: "dansk kanalorden",
    signature: "Fargerike fasader som nesten blir for høflige til å være sanne.",
    tags: ["danmark", "europa", "kanal"],
  },
  {
    id: "stockholm-gamla-stan",
    label: "Stortorget, Stockholm",
    country: "Sverige",
    continent: "Europa",
    lat: 59.3251,
    lon: 18.0708,
    heading: 188,
    pitch: 1,
    fov: 84,
    difficulty: "lett",
    theme: "svensk fasadeteater",
    signature: "For pent til at Norge får eie nordisk selvtillit alene.",
    tags: ["sverige", "europa", "gammelby"],
  },
  {
    id: "helsinki-senate-square",
    label: "Senaatintori, Helsinki",
    country: "Finland",
    continent: "Europa",
    lat: 60.1695,
    lon: 24.9522,
    heading: 8,
    pitch: 1,
    fov: 90,
    difficulty: "middels",
    theme: "nordisk monumentalro",
    signature: "Stille storhet med mer østlig nerve enn geoten liker.",
    tags: ["finland", "europa", "torg"],
  },
  {
    id: "gdansk-dlugi-targ",
    label: "Długi Targ, Gdańsk",
    country: "Polen",
    continent: "Europa",
    lat: 54.3487,
    lon: 18.6535,
    heading: 96,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "hansa, pastell og polsk snubletråd",
    signature: "Nederlandsk pynt med slavisk fotnote.",
    tags: ["polen", "europa", "hansa"],
  },
  {
    id: "prague-mala-strana",
    label: "Malostranské náměstí, Praha",
    country: "Tsjekkia",
    continent: "Europa",
    lat: 50.0881,
    lon: 14.4039,
    heading: 232,
    pitch: 2,
    fov: 86,
    difficulty: "middels",
    theme: "sentral-europeisk brosteinsteater",
    signature: "Tsjekkia gjør seg alltid litt for lett å undervurdere.",
    tags: ["tsjekkia", "europa", "brostein"],
  },
  {
    id: "budapest-chain-bridge",
    label: "Széchenyi lánchíd, Budapest",
    country: "Ungarn",
    continent: "Europa",
    lat: 47.498,
    lon: 19.0437,
    heading: 252,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "donau og imperialt sidesyn",
    signature: "Når broen er dramatisk nok, blir alle plutselig sikre.",
    tags: ["ungarn", "europa", "bro"],
  },
  {
    id: "ljubljana-dragon-bridge",
    label: "Zmajski most, Ljubljana",
    country: "Slovenia",
    continent: "Europa",
    lat: 46.0525,
    lon: 14.5104,
    heading: 130,
    pitch: 1,
    fov: 88,
    difficulty: "middels",
    theme: "alpeland med balkansk hvisking",
    signature: "For ryddig til Balkan, for dragepreget til Sveits.",
    tags: ["slovenia", "europa", "bro"],
  },
  {
    id: "dubrovnik-stradun",
    label: "Stradun, Dubrovnik",
    country: "Kroatia",
    continent: "Europa",
    lat: 42.641,
    lon: 18.109,
    heading: 72,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "adriatisk kalkstein og turistdisiplin",
    signature: "Marmoraktig trygghet før noen overtenker Middelhavet.",
    tags: ["kroatia", "europa", "adriaterhavet"],
  },
  {
    id: "split-riva",
    label: "Riva, Split",
    country: "Kroatia",
    continent: "Europa",
    lat: 43.5081,
    lon: 16.4402,
    heading: 148,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "palmer, stein og keiserlig restvarme",
    signature: "Kysten prøver å hjelpe, men Balkan nekter fasitgaranti.",
    tags: ["kroatia", "europa", "kyst"],
  },
  {
    id: "athens-plaka",
    label: "Plaka, Athen",
    country: "Hellas",
    continent: "Europa",
    lat: 37.9739,
    lon: 23.7295,
    heading: 44,
    pitch: 2,
    fov: 88,
    difficulty: "middels",
    theme: "gresk varme mellom hvitvegger",
    signature: "Når alfabetet hjelper for mye, må utsnittet bli trangt.",
    tags: ["hellas", "europa", "gater"],
  },
  {
    id: "thessaloniki-waterfront",
    label: "Nikis Avenue, Thessaloniki",
    country: "Hellas",
    continent: "Europa",
    lat: 40.6266,
    lon: 22.9484,
    heading: 116,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "egeisk byflate uten øygaranti",
    signature: "Hellas når det ikke gidder å være postkort.",
    tags: ["hellas", "europa", "kyst"],
  },
  {
    id: "naples-spaccanapoli",
    label: "Spaccanapoli, Napoli",
    country: "Italia",
    continent: "Europa",
    lat: 40.8498,
    lon: 14.2565,
    heading: 258,
    pitch: 1,
    fov: 88,
    difficulty: "middels",
    theme: "italiensk tetthet og gatespenning",
    signature: "Roma er for ryddig; Napoli lar fasaden krangle.",
    tags: ["italia", "europa", "by"],
  },
  {
    id: "palermo-quattro-canti",
    label: "Quattro Canti, Palermo",
    country: "Italia",
    continent: "Europa",
    lat: 38.1156,
    lon: 13.3614,
    heading: 318,
    pitch: 1,
    fov: 86,
    difficulty: "hard",
    theme: "siciliansk barokk i varmedis",
    signature: "Italia, men med et ekstra lag øy-mistanke.",
    tags: ["italia", "sicilia", "europa"],
  },
  {
    id: "valletta-st-george",
    label: "St George's Square, Valletta",
    country: "Malta",
    continent: "Europa",
    lat: 35.8997,
    lon: 14.5147,
    heading: 64,
    pitch: 1,
    fov: 88,
    difficulty: "hard",
    theme: "kalkstein, britisk ekko og middelhavsfelle",
    signature: "For tørt til England, for ordnet til spontan Spania.",
    tags: ["malta", "europa", "middelnav"],
  },
  {
    id: "bilbao-casco-viejo",
    label: "Casco Viejo, Bilbao",
    country: "Spania",
    continent: "Europa",
    lat: 43.2572,
    lon: -2.9249,
    heading: 220,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "baskisk byfølelse",
    signature: "Spania uten postkortlatskap, akkurat nok til forvirring.",
    tags: ["spania", "europa", "baskerland"],
  },
  {
    id: "granada-albaicin",
    label: "Albaicín, Granada",
    country: "Spania",
    continent: "Europa",
    lat: 37.1793,
    lon: -3.5922,
    heading: 142,
    pitch: 2,
    fov: 88,
    difficulty: "middels",
    theme: "andalusisk hvitveis",
    signature: "Når varme vegger faktisk kan være Spania.",
    tags: ["spania", "andalusia", "europa"],
  },
  {
    id: "lyon-vieux-lyon",
    label: "Vieux Lyon",
    country: "Frankrike",
    continent: "Europa",
    lat: 45.7605,
    lon: 4.8268,
    heading: 34,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "fransk bylag uten eiffeltvang",
    signature: "Når Frankrike gjemmer seg bak oker og smug.",
    tags: ["frankrike", "europa", "gammelby"],
  },
  {
    id: "strasbourg-petite-france",
    label: "Petite France, Strasbourg",
    country: "Frankrike",
    continent: "Europa",
    lat: 48.5817,
    lon: 7.7425,
    heading: 190,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "bindingsverk med fransk pass",
    signature: "Tyskland banker på, men fasiten sier baguette med papirarbeid.",
    tags: ["frankrike", "europa", "bindingsverk"],
  },
  {
    id: "bruges-market-square",
    label: "Markt, Brugge",
    country: "Belgia",
    continent: "Europa",
    lat: 51.2089,
    lon: 3.2242,
    heading: 272,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "flamsk postkortdisiplin",
    signature: "For eventyrlig til Nederland, for lavt til Østerrike.",
    tags: ["belgia", "europa", "torg"],
  },
  {
    id: "luxembourg-grund",
    label: "Grund, Luxembourg",
    country: "Luxembourg",
    continent: "Europa",
    lat: 49.6094,
    lon: 6.1348,
    heading: 114,
    pitch: -1,
    fov: 88,
    difficulty: "hard",
    theme: "liten stat med stor steinmur",
    signature: "Når alle forslag virker nesten riktige og derfor farlige.",
    tags: ["luxembourg", "europa", "dal"],
  },
  {
    id: "amsterdam-jordaan",
    label: "Jordaan, Amsterdam",
    country: "Nederland",
    continent: "Europa",
    lat: 52.3731,
    lon: 4.8803,
    heading: 28,
    pitch: 0,
    fov: 86,
    difficulty: "lett",
    theme: "kanaler uten belgisk unnskyldning",
    signature: "Sykkel, vann og selvtillit i samme bilde.",
    tags: ["nederland", "europa", "kanal"],
  },
  {
    id: "hamburg-speicherstadt",
    label: "Speicherstadt, Hamburg",
    country: "Tyskland",
    continent: "Europa",
    lat: 53.5444,
    lon: 9.9882,
    heading: 306,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "tegl, vann og nordtysk alvor",
    signature: "Tyskland når det prøver å ligne en havn med hemmeligheter.",
    tags: ["tyskland", "europa", "havn"],
  },
  {
    id: "vienna-graben",
    label: "Graben, Wien",
    country: "Østerrike",
    continent: "Europa",
    lat: 48.2088,
    lon: 16.3694,
    heading: 92,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "keiserlig fasadekontroll",
    signature: "Når byen er for pyntet til at geoten tør si Budapest.",
    tags: ["osterrike", "europa", "by"],
  },
  {
    id: "innsbruck-maria-theresien",
    label: "Maria-Theresien-Straße, Innsbruck",
    country: "Østerrike",
    continent: "Europa",
    lat: 47.2654,
    lon: 11.3947,
    heading: 350,
    pitch: 1,
    fov: 90,
    difficulty: "lett",
    theme: "alper i sidesynet",
    signature: "Fjellene forsøker å rope fasit, men vi holder igjen utsnittet.",
    tags: ["osterrike", "europa", "alper"],
  },
  {
    id: "brasov-council-square",
    label: "Piața Sfatului, Brașov",
    country: "Romania",
    continent: "Europa",
    lat: 45.6427,
    lon: 25.5887,
    heading: 176,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "karpatisk torglogikk",
    signature: "Sentral-Europa, men skogen står og følger med.",
    tags: ["romania", "europa", "karpatene"],
  },
  {
    id: "sofia-vitosha-boulevard",
    label: "Vitosha Boulevard, Sofia",
    country: "Bulgaria",
    continent: "Europa",
    lat: 42.6919,
    lon: 23.3192,
    heading: 178,
    pitch: 1,
    fov: 88,
    difficulty: "hard",
    theme: "balkansk boulevard med fjellhint",
    signature: "Ikke alt i Balkan er rot, men alt kan bli diskusjon.",
    tags: ["bulgaria", "europa", "balkan"],
  },
  {
    id: "skopje-old-bazaar",
    label: "Old Bazaar, Skopje",
    country: "Nord-Makedonia",
    continent: "Europa",
    lat: 42.0001,
    lon: 21.4361,
    heading: 60,
    pitch: 1,
    fov: 86,
    difficulty: "hard",
    theme: "balkanbasar og kontinenturo",
    signature: "Europa med nok osmansk ekko til å forstyrre kompasset.",
    tags: ["nord-makedonia", "europa", "balkan"],
  },
  {
    id: "kotor-old-town",
    label: "Stari Grad, Kotor",
    country: "Montenegro",
    continent: "Europa",
    lat: 42.4258,
    lon: 18.7712,
    heading: 242,
    pitch: 1,
    fov: 86,
    difficulty: "hard",
    theme: "fjellvegg ved adriatisk smug",
    signature: "Kroatia-følelsen får montenegrinsk motstand.",
    tags: ["montenegro", "europa", "adriaterhavet"],
  },
  {
    id: "reykjavik-hallgrimskirkja",
    label: "Skólavörðustígur, Reykjavík",
    country: "Island",
    continent: "Europa",
    lat: 64.142,
    lon: -21.9275,
    heading: 82,
    pitch: 1,
    fov: 90,
    difficulty: "middels",
    theme: "nordisk lavaorden",
    signature: "Når himmelen er lav og husene nekter fastlandet.",
    tags: ["island", "europa", "nord"],
  },
  {
    id: "taipei-dihua-street",
    label: "Dihua Street, Taipei",
    country: "Taiwan",
    continent: "Asia",
    lat: 25.0566,
    lon: 121.5106,
    heading: 18,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "østasiatisk handelstetthet",
    signature: "Skilt, scootere og presisjon i et litt for travelt hjørne.",
    tags: ["taiwan", "asia", "by"],
  },
  {
    id: "hong-kong-sheung-wan",
    label: "Sheung Wan, Hongkong",
    country: "Hongkong",
    continent: "Asia",
    lat: 22.285,
    lon: 114.1496,
    heading: 104,
    pitch: 4,
    fov: 86,
    difficulty: "hard",
    theme: "vertikal bylesning",
    signature: "Når alt peker oppover og geoten likevel ser feil havn.",
    tags: ["hongkong", "asia", "skilt"],
  },
  {
    id: "singapore-kampong-glam",
    label: "Kampong Glam, Singapore",
    country: "Singapore",
    continent: "Asia",
    lat: 1.3029,
    lon: 103.8599,
    heading: 286,
    pitch: 1,
    fov: 88,
    difficulty: "middels",
    theme: "tropisk orden med moskekuppel",
    signature: "For rent til kaos, for varmt til Europa.",
    tags: ["singapore", "asia", "tropisk"],
  },
  {
    id: "kuala-lumpur-merdeka",
    label: "Merdeka Square, Kuala Lumpur",
    country: "Malaysia",
    continent: "Asia",
    lat: 3.1478,
    lon: 101.6932,
    heading: 210,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "kolonigrønt og tropisk byvarme",
    signature: "Malaysia later som det er enkelt helt til flaggstangen blander seg.",
    tags: ["malaysia", "asia", "by"],
  },
  {
    id: "bangkok-yaowarat",
    label: "Yaowarat Road, Bangkok",
    country: "Thailand",
    continent: "Asia",
    lat: 13.7398,
    lon: 100.5112,
    heading: 118,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "skiltkaos med nattmarkedenergi",
    signature: "Når Thailand skrur opp volumet uten å gi fra seg fasiten.",
    tags: ["thailand", "asia", "by"],
  },
  {
    id: "chiang-mai-old-city",
    label: "Old City, Chiang Mai",
    country: "Thailand",
    continent: "Asia",
    lat: 18.7883,
    lon: 98.9853,
    heading: 44,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "nordthailandsk tempelro",
    signature: "Ikke Bangkok, og nettopp derfor farligere.",
    tags: ["thailand", "asia", "tempel"],
  },
  {
    id: "hanoi-old-quarter",
    label: "Old Quarter, Hanoi",
    country: "Vietnam",
    continent: "Asia",
    lat: 21.034,
    lon: 105.8503,
    heading: 328,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "scootere og fransk etterklang",
    signature: "Vietnam når gaten aldri står stille.",
    tags: ["vietnam", "asia", "by"],
  },
  {
    id: "hoi-an-lanterns",
    label: "Ancient Town, Hội An",
    country: "Vietnam",
    continent: "Asia",
    lat: 15.8801,
    lon: 108.338,
    heading: 82,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "lanterner og gul byvarme",
    signature: "For vakkert til at noen klarer å holde hodet kaldt.",
    tags: ["vietnam", "asia", "gammelby"],
  },
  {
    id: "jakarta-kota-tua",
    label: "Kota Tua, Jakarta",
    country: "Indonesia",
    continent: "Asia",
    lat: -6.1352,
    lon: 106.8133,
    heading: 134,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "koloniflate i tropisk støy",
    signature: "Nederlandsk arv under indonesisk himmel.",
    tags: ["indonesia", "asia", "by"],
  },
  {
    id: "yogyakarta-malioboro",
    label: "Malioboro Street, Yogyakarta",
    country: "Indonesia",
    continent: "Asia",
    lat: -7.7927,
    lon: 110.3658,
    heading: 12,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "javanesisk hovedgatefølelse",
    signature: "Indonesia uten strandhjelp er en prøvelse med vilje.",
    tags: ["indonesia", "asia", "java"],
  },
  {
    id: "manila-intramuros",
    label: "Intramuros, Manila",
    country: "Filippinene",
    continent: "Asia",
    lat: 14.5909,
    lon: 120.974,
    heading: 248,
    pitch: 1,
    fov: 88,
    difficulty: "hard",
    theme: "spansk mur under tropisk press",
    signature: "Når Latin-Amerika-følelsen havner i Asia.",
    tags: ["filippinene", "asia", "kolonial"],
  },
  {
    id: "cebu-colon-street",
    label: "Colon Street, Cebu",
    country: "Filippinene",
    continent: "Asia",
    lat: 10.2938,
    lon: 123.9012,
    heading: 82,
    pitch: 0,
    fov: 88,
    difficulty: "absurd",
    theme: "filippinsk bylesning uten Manila",
    signature: "Tropisk tett, men ikke helt der autopiloten vil.",
    tags: ["filippinene", "asia", "by"],
  },
  {
    id: "kyoto-gion",
    label: "Gion, Kyoto",
    country: "Japan",
    continent: "Asia",
    lat: 35.0037,
    lon: 135.7788,
    heading: 188,
    pitch: 0,
    fov: 84,
    difficulty: "middels",
    theme: "japansk tradisjon i lav høyde",
    signature: "Ikke alt i Japan trenger neon for å være farlig.",
    tags: ["japan", "asia", "gammelby"],
  },
  {
    id: "kanazawa-higashi-chaya",
    label: "Higashi Chaya, Kanazawa",
    country: "Japan",
    continent: "Asia",
    lat: 36.5729,
    lon: 136.6661,
    heading: 96,
    pitch: 0,
    fov: 84,
    difficulty: "hard",
    theme: "trehus og japansk presisjon",
    signature: "Kyoto-følelse uten Kyoto-garanti.",
    tags: ["japan", "asia", "trehus"],
  },
  {
    id: "osaka-shinsekai",
    label: "Shinsekai, Osaka",
    country: "Japan",
    continent: "Asia",
    lat: 34.6525,
    lon: 135.5063,
    heading: 18,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "japansk neonlyd i dagslys",
    signature: "Osaka roper høyere enn Tokyo, og det er poenget.",
    tags: ["japan", "asia", "by"],
  },
  {
    id: "busan-gamcheon",
    label: "Gamcheon Culture Village, Busan",
    country: "Sør-Korea",
    continent: "Asia",
    lat: 35.0975,
    lon: 129.0106,
    heading: 308,
    pitch: -3,
    fov: 90,
    difficulty: "middels",
    theme: "fargerik koreansk åsside",
    signature: "Seoul-refleksen får motstand fra havluft og bakker.",
    tags: ["sor-korea", "asia", "farger"],
  },
  {
    id: "jeju-seogwipo",
    label: "Seogwipo, Jeju",
    country: "Sør-Korea",
    continent: "Asia",
    lat: 33.2496,
    lon: 126.561,
    heading: 152,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "koreansk øyfølelse",
    signature: "Når Korea plutselig får palmer i margen.",
    tags: ["sor-korea", "asia", "oy"],
  },
  {
    id: "yerevan-cascade",
    label: "Cascade, Jerevan",
    country: "Armenia",
    continent: "Asia",
    lat: 40.1907,
    lon: 44.5155,
    heading: 184,
    pitch: 2,
    fov: 88,
    difficulty: "hard",
    theme: "kaukasisk trapp og steinvarme",
    signature: "Europa-følelsen får armensk korrektur.",
    tags: ["armenia", "asia", "kaukasus"],
  },
  {
    id: "almaty-panfilov",
    label: "Panfilov Park, Almaty",
    country: "Kasakhstan",
    continent: "Asia",
    lat: 43.2585,
    lon: 76.9557,
    heading: 210,
    pitch: 1,
    fov: 90,
    difficulty: "absurd",
    theme: "sentralasiatisk parkro",
    signature: "Når Asia er bredere enn magefølelsen.",
    tags: ["kasakhstan", "asia", "park"],
  },
  {
    id: "bishkek-ala-too",
    label: "Ala-Too Square, Bisjkek",
    country: "Kirgisistan",
    continent: "Asia",
    lat: 42.8769,
    lon: 74.603,
    heading: 90,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "sentralasiatisk monumentalflate",
    signature: "Et torg som gjør alle kontinentteorier litt nervøse.",
    tags: ["kirgisistan", "asia", "torg"],
  },
  {
    id: "cairo-zamalek",
    label: "Zamalek, Kairo",
    country: "Egypt",
    continent: "Afrika",
    lat: 30.0606,
    lon: 31.2196,
    heading: 174,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "nilby med støvete eleganse",
    signature: "Afrika, Midtøsten og storbytretthet i samme gate.",
    tags: ["egypt", "afrika", "by"],
  },
  {
    id: "alexandria-corniche",
    label: "Corniche, Alexandria",
    country: "Egypt",
    continent: "Afrika",
    lat: 31.2001,
    lon: 29.9187,
    heading: 64,
    pitch: 0,
    fov: 92,
    difficulty: "hard",
    theme: "middelhav med egyptisk støvkant",
    signature: "Ikke Hellas, selv om havet prøver å forhandle.",
    tags: ["egypt", "afrika", "kyst"],
  },
  {
    id: "tunis-sidi-bou-said",
    label: "Sidi Bou Said, Tunis",
    country: "Tunisia",
    continent: "Afrika",
    lat: 36.8702,
    lon: 10.3417,
    heading: 220,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "blåhvitt nordafrikansk bedrag",
    signature: "Hellas-følelsen får tunisisk passkontroll.",
    tags: ["tunisia", "afrika", "middelnav"],
  },
  {
    id: "casablanca-habous",
    label: "Quartier Habous, Casablanca",
    country: "Marokko",
    continent: "Afrika",
    lat: 33.5738,
    lon: -7.6037,
    heading: 118,
    pitch: 1,
    fov: 88,
    difficulty: "middels",
    theme: "marokkansk byorden",
    signature: "Marrakesh-refleksen får en hvitere, mer urban slektning.",
    tags: ["marokko", "afrika", "by"],
  },
  {
    id: "fes-bab-boujloud",
    label: "Bab Bou Jeloud, Fès",
    country: "Marokko",
    continent: "Afrika",
    lat: 34.0629,
    lon: -4.9834,
    heading: 300,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "medinaport og nordafrikansk mønster",
    signature: "Når porten nesten sier landet høyt, men ikke helt.",
    tags: ["marokko", "afrika", "medina"],
  },
  {
    id: "accra-osu",
    label: "Oxford Street, Osu, Accra",
    country: "Ghana",
    continent: "Afrika",
    lat: 5.556,
    lon: -0.1819,
    heading: 84,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "vestafrikansk gatehandel",
    signature: "Afrika uten safarihjelp er ren embetseksamen.",
    tags: ["ghana", "afrika", "by"],
  },
  {
    id: "lagos-marina",
    label: "Marina, Lagos",
    country: "Nigeria",
    continent: "Afrika",
    lat: 6.4527,
    lon: 3.3958,
    heading: 92,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "megaby med vestafrikansk trykk",
    signature: "Når storbyen nekter å være ryddig nok for magefølelsen.",
    tags: ["nigeria", "afrika", "by"],
  },
  {
    id: "nairobi-karen",
    label: "Karen, Nairobi",
    country: "Kenya",
    continent: "Afrika",
    lat: -1.3197,
    lon: 36.7073,
    heading: 156,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "østafrikansk grønt og veiro",
    signature: "Kenya uten åpenbar savanne er ubehagelig sunt.",
    tags: ["kenya", "afrika", "vei"],
  },
  {
    id: "mombasa-old-town",
    label: "Old Town, Mombasa",
    country: "Kenya",
    continent: "Afrika",
    lat: -4.0623,
    lon: 39.6776,
    heading: 42,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "swahilikyst og smale gater",
    signature: "Afrika møter Indiahavet og gjør alle litt for sikre.",
    tags: ["kenya", "afrika", "kyst"],
  },
  {
    id: "johannesburg-maboneng",
    label: "Maboneng, Johannesburg",
    country: "Sør-Afrika",
    continent: "Afrika",
    lat: -26.2044,
    lon: 28.0597,
    heading: 268,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "sørafrikansk urban kant",
    signature: "Ikke Cape Town, og det er hele prøven.",
    tags: ["sor-afrika", "afrika", "by"],
  },
  {
    id: "durban-golden-mile",
    label: "Golden Mile, Durban",
    country: "Sør-Afrika",
    continent: "Afrika",
    lat: -29.8526,
    lon: 31.0386,
    heading: 32,
    pitch: 0,
    fov: 92,
    difficulty: "middels",
    theme: "indiahav og sørafrikansk kyst",
    signature: "Palmer betyr ikke Karibia når Durban blander seg.",
    tags: ["sor-afrika", "afrika", "kyst"],
  },
  {
    id: "pretoria-union-buildings",
    label: "Union Buildings, Pretoria",
    country: "Sør-Afrika",
    continent: "Afrika",
    lat: -25.7407,
    lon: 28.2121,
    heading: 288,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "sørafrikansk monumentalhage",
    signature: "For ryddig til safari, for varmt til Europa.",
    tags: ["sor-afrika", "afrika", "monument"],
  },
  {
    id: "stellenbosch-dorp",
    label: "Dorp Street, Stellenbosch",
    country: "Sør-Afrika",
    continent: "Afrika",
    lat: -33.9368,
    lon: 18.8613,
    heading: 104,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "kappkolonial ro",
    signature: "Nederlandsk skygge under afrikansk sol.",
    tags: ["sor-afrika", "afrika", "kolonial"],
  },
  {
    id: "kigali-nyamirambo",
    label: "Nyamirambo, Kigali",
    country: "Rwanda",
    continent: "Afrika",
    lat: -1.974,
    lon: 30.043,
    heading: 118,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "østafrikansk åssideby",
    signature: "Når ryddighet og bakker ikke peker dit du tror.",
    tags: ["rwanda", "afrika", "by"],
  },
  {
    id: "buenos-aires-san-telmo",
    label: "San Telmo, Buenos Aires",
    country: "Argentina",
    continent: "Sør-Amerika",
    lat: -34.6215,
    lon: -58.3736,
    heading: 14,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "søramerikansk Europa-finte",
    signature: "Buenos Aires lar alle føle seg kloke litt for tidlig.",
    tags: ["argentina", "sor-amerika", "by"],
  },
  {
    id: "buenos-aires-la-boca",
    label: "La Boca, Buenos Aires",
    country: "Argentina",
    continent: "Sør-Amerika",
    lat: -34.6377,
    lon: -58.3615,
    heading: 286,
    pitch: 0,
    fov: 86,
    difficulty: "lett",
    theme: "fargekaos ved rio de la plata",
    signature: "Når fasadene nesten danser tango på egen hånd.",
    tags: ["argentina", "sor-amerika", "farger"],
  },
  {
    id: "santiago-lastarria",
    label: "Barrio Lastarria, Santiago",
    country: "Chile",
    continent: "Sør-Amerika",
    lat: -33.4388,
    lon: -70.6392,
    heading: 166,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "chilensk byro med andesbakgrunn",
    signature: "Sør-Amerika når fjellene står som dommere i bakrommet.",
    tags: ["chile", "sor-amerika", "by"],
  },
  {
    id: "valdivia-costanera",
    label: "Costanera, Valdivia",
    country: "Chile",
    continent: "Sør-Amerika",
    lat: -39.8156,
    lon: -73.2459,
    heading: 74,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "sørchilensk vann og lav himmel",
    signature: "Når Chile plutselig later som det er Nord-Europa.",
    tags: ["chile", "sor-amerika", "kyst"],
  },
  {
    id: "punta-arenas-plaza",
    label: "Plaza Muñoz Gamero, Punta Arenas",
    country: "Chile",
    continent: "Sør-Amerika",
    lat: -53.1638,
    lon: -70.9171,
    heading: 214,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "patagonsk bykulde",
    signature: "Sør-Amerika med ulljakke og verdensende i blikket.",
    tags: ["chile", "patagonia", "sor-amerika"],
  },
  {
    id: "lima-barranco",
    label: "Barranco, Lima",
    country: "Peru",
    continent: "Sør-Amerika",
    lat: -12.1491,
    lon: -77.0219,
    heading: 122,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "peruansk kystbohem",
    signature: "Peru uten fjell er fortsatt Peru, bare mer slu.",
    tags: ["peru", "sor-amerika", "kyst"],
  },
  {
    id: "arequipa-plaza",
    label: "Plaza de Armas, Arequipa",
    country: "Peru",
    continent: "Sør-Amerika",
    lat: -16.3989,
    lon: -71.5369,
    heading: 310,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "hvit vulkanby i andeslys",
    signature: "Ikke Cusco, men høyden vil fortsatt ha ordet.",
    tags: ["peru", "sor-amerika", "andes"],
  },
  {
    id: "quito-la-ronda",
    label: "La Ronda, Quito",
    country: "Ecuador",
    continent: "Sør-Amerika",
    lat: -0.2241,
    lon: -78.5138,
    heading: 28,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "andinsk gammelby",
    signature: "Når høyde, farger og brostein peker mot ekvator.",
    tags: ["ecuador", "sor-amerika", "andes"],
  },
  {
    id: "guayaquil-malecon",
    label: "Malecón 2000, Guayaquil",
    country: "Ecuador",
    continent: "Sør-Amerika",
    lat: -2.1906,
    lon: -79.8818,
    heading: 188,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "ekvatorial elvepromenade",
    signature: "Ecuador uten fjell gjør kompasset mer irritert.",
    tags: ["ecuador", "sor-amerika", "elv"],
  },
  {
    id: "bogota-candelaria",
    label: "La Candelaria, Bogotá",
    country: "Colombia",
    continent: "Sør-Amerika",
    lat: 4.5966,
    lon: -74.0732,
    heading: 336,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "kolombiansk brostein i høyden",
    signature: "Farger, fjell og altfor mange selvsikre teorier.",
    tags: ["colombia", "sor-amerika", "by"],
  },
  {
    id: "medellin-poblado",
    label: "El Poblado, Medellín",
    country: "Colombia",
    continent: "Sør-Amerika",
    lat: 6.2087,
    lon: -75.5679,
    heading: 76,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "grønn dalby",
    signature: "Colombia når byen ligger og later som den er lettlest.",
    tags: ["colombia", "sor-amerika", "dal"],
  },
  {
    id: "cartagena-walled-city",
    label: "Ciudad Amurallada, Cartagena",
    country: "Colombia",
    continent: "Sør-Amerika",
    lat: 10.4236,
    lon: -75.5506,
    heading: 112,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "karibisk kolonifarge",
    signature: "Sør-Amerika med Karibia i skjortekragen.",
    tags: ["colombia", "karibia", "sor-amerika"],
  },
  {
    id: "asuncion-costanera",
    label: "Costanera de Asunción",
    country: "Paraguay",
    continent: "Sør-Amerika",
    lat: -25.2805,
    lon: -57.6362,
    heading: 78,
    pitch: 0,
    fov: 90,
    difficulty: "absurd",
    theme: "innlands-søramerika med elveluft",
    signature: "Paraguay er stedet alle glemmer til det er for sent.",
    tags: ["paraguay", "sor-amerika", "elv"],
  },
  {
    id: "colonia-sacramento",
    label: "Barrio Histórico, Colonia del Sacramento",
    country: "Uruguay",
    continent: "Sør-Amerika",
    lat: -34.4729,
    lon: -57.8515,
    heading: 36,
    pitch: 0,
    fov: 86,
    difficulty: "hard",
    theme: "uruguayansk koloniro",
    signature: "For stille til Argentina, for brosteinete til autopilot.",
    tags: ["uruguay", "sor-amerika", "gammelby"],
  },
  {
    id: "sucre-plaza",
    label: "Plaza 25 de Mayo, Sucre",
    country: "Bolivia",
    continent: "Sør-Amerika",
    lat: -19.0477,
    lon: -65.2595,
    heading: 240,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "boliviansk hvitby",
    signature: "Bolivia med penere dress enn La Paz-refleksen forventer.",
    tags: ["bolivia", "sor-amerika", "andes"],
  },
  {
    id: "mexico-city-condesa",
    label: "Condesa, Mexico by",
    country: "Mexico",
    continent: "Nord-Amerika",
    lat: 19.4115,
    lon: -99.1712,
    heading: 126,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "bladgrønn meksikansk byro",
    signature: "Mexico uten kaktus, men med nok fortau til mistanke.",
    tags: ["mexico", "nord-amerika", "by"],
  },
  {
    id: "oaxaca-zocalo",
    label: "Zócalo, Oaxaca",
    country: "Mexico",
    continent: "Nord-Amerika",
    lat: 17.0607,
    lon: -96.7254,
    heading: 198,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "meksikansk torgvarme",
    signature: "Fargene er hjelpsomme, men landet er større enn instinktet.",
    tags: ["mexico", "nord-amerika", "torg"],
  },
  {
    id: "merida-paseo-montejo",
    label: "Paseo de Montejo, Mérida",
    country: "Mexico",
    continent: "Nord-Amerika",
    lat: 20.9856,
    lon: -89.6168,
    heading: 22,
    pitch: 0,
    fov: 90,
    difficulty: "hard",
    theme: "yucatansk boulevard",
    signature: "Mexico når varmen blir flatere og hvitere.",
    tags: ["mexico", "nord-amerika", "yucatan"],
  },
  {
    id: "guanajuato-centro",
    label: "Centro, Guanajuato",
    country: "Mexico",
    continent: "Nord-Amerika",
    lat: 21.017,
    lon: -101.2574,
    heading: 306,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "fargerik meksikansk fjellby",
    signature: "Når gatene klatrer og fasadene nekter nøytralitet.",
    tags: ["mexico", "nord-amerika", "farger"],
  },
  {
    id: "quebec-petit-champlain",
    label: "Petit-Champlain, Québec",
    country: "Canada",
    continent: "Nord-Amerika",
    lat: 46.8122,
    lon: -71.2039,
    heading: 38,
    pitch: 1,
    fov: 86,
    difficulty: "middels",
    theme: "fransk nordamerika",
    signature: "Europa i vinterjakke, med Canada som stempel.",
    tags: ["canada", "nord-amerika", "gammelby"],
  },
  {
    id: "st-johns-signal-hill",
    label: "Signal Hill, St. John's",
    country: "Canada",
    continent: "Nord-Amerika",
    lat: 47.5707,
    lon: -52.681,
    heading: 252,
    pitch: -2,
    fov: 92,
    difficulty: "hard",
    theme: "atlantisk kant og farger",
    signature: "Canada når havet gjør alt litt mer irsk.",
    tags: ["canada", "nord-amerika", "kyst"],
  },
  {
    id: "new-orleans-marigny",
    label: "Faubourg Marigny, New Orleans",
    country: "USA",
    continent: "Nord-Amerika",
    lat: 29.9657,
    lon: -90.055,
    heading: 142,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "sørstatsfarge og balkonguro",
    signature: "USA, men med fransk aksent og dårligere magefølelse.",
    tags: ["usa", "nord-amerika", "sorstat"],
  },
  {
    id: "savannah-river-street",
    label: "River Street, Savannah",
    country: "USA",
    continent: "Nord-Amerika",
    lat: 32.0809,
    lon: -81.0896,
    heading: 78,
    pitch: 0,
    fov: 90,
    difficulty: "middels",
    theme: "murstein og sørstatsfukt",
    signature: "Amerika når brosteinene prøver å høres europeiske ut.",
    tags: ["usa", "nord-amerika", "sorstat"],
  },
  {
    id: "san-juan-old-city",
    label: "Viejo San Juan",
    country: "Puerto Rico",
    continent: "Nord-Amerika",
    lat: 18.4655,
    lon: -66.1167,
    heading: 306,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "karibisk kolonifarge",
    signature: "Spansk farge med amerikansk fotnote i lomma.",
    tags: ["puerto-rico", "karibia", "nord-amerika"],
  },
  {
    id: "charleston-rainbow-row",
    label: "Rainbow Row, Charleston",
    country: "USA",
    continent: "Nord-Amerika",
    lat: 32.7774,
    lon: -79.9286,
    heading: 208,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "pastell og sørstatsorden",
    signature: "For pent til Florida, for lavt til New England.",
    tags: ["usa", "nord-amerika", "farger"],
  },
  {
    id: "vancouver-gastown",
    label: "Gastown, Vancouver",
    country: "Canada",
    continent: "Nord-Amerika",
    lat: 49.2833,
    lon: -123.1067,
    heading: 96,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "vestkyst, murstein og fjellmistanke",
    signature: "Canada når byen prøver å være Seattle med høfligere puls.",
    tags: ["canada", "nord-amerika", "vestkyst"],
  },
  {
    id: "sydney-the-rocks",
    label: "The Rocks, Sydney",
    country: "Australia",
    continent: "Oseania",
    lat: -33.8599,
    lon: 151.209,
    heading: 154,
    pitch: 0,
    fov: 88,
    difficulty: "lett",
    theme: "australsk havnekoloni",
    signature: "Når engelsk skilt ikke betyr England, men solen sier sitt.",
    tags: ["australia", "oseania", "havn"],
  },
  {
    id: "melbourne-fitzroy",
    label: "Brunswick Street, Fitzroy",
    country: "Australia",
    continent: "Oseania",
    lat: -37.8009,
    lon: 144.9784,
    heading: 18,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "australsk murstein og kafékultur",
    signature: "Australia uten strand er alltid litt mer slu.",
    tags: ["australia", "oseania", "by"],
  },
  {
    id: "hobart-salamanca",
    label: "Salamanca Place, Hobart",
    country: "Australia",
    continent: "Oseania",
    lat: -42.8864,
    lon: 147.3318,
    heading: 94,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "tasmanisk steinro",
    signature: "Australia med kjøligere skuldre og eldre mur.",
    tags: ["australia", "tasmania", "oseania"],
  },
  {
    id: "adelaide-glenelg",
    label: "Glenelg, Adelaide",
    country: "Australia",
    continent: "Oseania",
    lat: -34.9806,
    lon: 138.5127,
    heading: 270,
    pitch: 0,
    fov: 92,
    difficulty: "middels",
    theme: "australsk strandforstad",
    signature: "Kysten hjelper, men byen nekter å være Sydney.",
    tags: ["australia", "oseania", "kyst"],
  },
  {
    id: "perth-fremantle",
    label: "Fremantle, Perth",
    country: "Australia",
    continent: "Oseania",
    lat: -32.0569,
    lon: 115.7439,
    heading: 128,
    pitch: 0,
    fov: 88,
    difficulty: "hard",
    theme: "vestaustralsk havnevarme",
    signature: "Australia flytter seg vestover og tar selvtilliten med.",
    tags: ["australia", "oseania", "havn"],
  },
  {
    id: "darwin-waterfront",
    label: "Darwin Waterfront",
    country: "Australia",
    continent: "Oseania",
    lat: -12.4668,
    lon: 130.8468,
    heading: 226,
    pitch: 0,
    fov: 92,
    difficulty: "hard",
    theme: "tropisk Australia",
    signature: "Når Australia plutselig later som det er Sørøst-Asia.",
    tags: ["australia", "oseania", "tropisk"],
  },
  {
    id: "auckland-ponsonby",
    label: "Ponsonby Road, Auckland",
    country: "New Zealand",
    continent: "Oseania",
    lat: -36.8546,
    lon: 174.7466,
    heading: 342,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "kiwiby uten postkortfjell",
    signature: "New Zealand når det forsøker å se hverdagslig ut.",
    tags: ["new-zealand", "oseania", "by"],
  },
  {
    id: "dunedin-railway-station",
    label: "Dunedin Railway Station",
    country: "New Zealand",
    continent: "Oseania",
    lat: -45.8759,
    lon: 170.5089,
    heading: 238,
    pitch: 0,
    fov: 88,
    difficulty: "middels",
    theme: "skotsk ekko ved stillehavskant",
    signature: "Når New Zealand tar på seg gamle britiske klær.",
    tags: ["new-zealand", "oseania", "jernbane"],
  },
  {
    id: "queenstown-waterfront",
    label: "Queenstown Waterfront",
    country: "New Zealand",
    continent: "Oseania",
    lat: -45.0312,
    lon: 168.6626,
    heading: 214,
    pitch: -2,
    fov: 92,
    difficulty: "lett",
    theme: "fjell, vann og kiwiteater",
    signature: "Når landskapet nesten jukser på geotens vegne.",
    tags: ["new-zealand", "oseania", "fjell"],
  },
  {
    id: "christchurch-new-regent",
    label: "New Regent Street, Christchurch",
    country: "New Zealand",
    continent: "Oseania",
    lat: -43.5294,
    lon: 172.6383,
    heading: 42,
    pitch: 0,
    fov: 86,
    difficulty: "middels",
    theme: "pastellkoloni i sør",
    signature: "New Zealand med farger som virker for planlagt.",
    tags: ["new-zealand", "oseania", "by"],
  },
];

function googleMapsServerApiKey() {
  return process.env.GOOGLE_MAPS_SERVER_API_KEY || process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "";
}

export function getSlowGeoMonthlyRoundCap() {
  const parsed = Number(process.env.SLOWGEO_MONTHLY_ROUND_CAP ?? "40");
  if (!Number.isFinite(parsed)) return 40;
  return Math.max(0, Math.floor(parsed));
}

function normalizedSet(values: string[]) {
  return new Set(values.map((value) => value.trim()).filter(Boolean));
}

function shuffledCandidates(excludeIds: string[]) {
  const excluded = normalizedSet(excludeIds);
  const available = slowGeoCandidates.filter((candidate) => !excluded.has(candidate.id));
  return [...available].sort(() => Math.random() - 0.5);
}

function challengeFromCandidate(
  candidate: StreetViewCandidate,
  metadata: StreetViewMetadataResponse | null,
): SlowGeoChallenge {
  const metadataLat = metadata?.location?.lat;
  const metadataLon = metadata?.location?.lng;

  return {
    id: randomUUID(),
    candidateId: candidate.id,
    source: "google_street_view",
    lat: typeof metadataLat === "number" ? metadataLat : candidate.lat,
    lon: typeof metadataLon === "number" ? metadataLon : candidate.lon,
    label: candidate.label,
    country: candidate.country,
    continent: candidate.continent,
    heading: candidate.heading,
    pitch: candidate.pitch ?? 0,
    fov: candidate.fov ?? 90,
    panoId: metadata?.pano_id,
    imageDate: metadata?.date,
    copyright: metadata?.copyright,
    difficulty: candidate.difficulty,
    theme: candidate.theme,
    signature: candidate.signature,
    tags: candidate.tags,
    createdAt: new Date().toISOString(),
  };
}

function attributionHintsForCandidate(candidate: StreetViewCandidate) {
  return [
    candidate.id,
    candidate.label,
    candidate.country,
    candidate.continent,
    candidate.theme,
    candidate.signature,
    ...candidate.tags,
  ];
}

async function fetchMetadata(candidate: StreetViewCandidate, apiKey: string) {
  const params = new URLSearchParams({
    location: `${candidate.lat},${candidate.lon}`,
    radius: "80",
    source: "outdoor",
    key: apiKey,
  });
  const response = await fetch(`https://maps.googleapis.com/maps/api/streetview/metadata?${params.toString()}`, {
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(`Google Street View metadata svarte med HTTP ${response.status}.`);
  }

  return (await response.json()) as StreetViewMetadataResponse;
}

export async function createStreetViewChallenge({
  excludeCandidateIds = [],
  excludePanoIds = [],
  requirePanoId = false,
}: {
  excludeCandidateIds?: string[];
  excludePanoIds?: string[];
  requirePanoId?: boolean;
} = {}) {
  const candidates = shuffledCandidates(excludeCandidateIds);
  if (candidates.length === 0) {
    throw new Error(slowGeoPoolExhaustedMessage);
  }
  const apiKey = googleMapsServerApiKey();
  const excludedPanoIds = normalizedSet(excludePanoIds);

  if (!apiKey) {
    if (requirePanoId) {
      throw new Error("Panorama-modus krever Google Street View metadata og gyldig pano-ID.");
    }
    return challengeFromCandidate(candidates[0], null);
  }

  let lastStatus = "";
  for (const candidate of candidates) {
    const metadata = await fetchMetadata(candidate, apiKey);
    lastStatus = metadata.status;
    if (metadata.status === "OK" && metadata.pano_id) {
      if (excludedPanoIds.has(metadata.pano_id)) {
        lastStatus = "USED_PANO";
        continue;
      }
      if (!isSafeSlowGeoAttribution(metadata.copyright, attributionHintsForCandidate(candidate))) {
        lastStatus = "UNSAFE_ATTRIBUTION";
        continue;
      }
      return challengeFromCandidate(candidate, metadata);
    }
    if (
      metadata.status === "REQUEST_DENIED" ||
      metadata.status === "OVER_QUERY_LIMIT" ||
      metadata.status === "INVALID_REQUEST"
    ) {
      throw new Error(metadata.error_message || `Google Street View metadata avviste forespørselen: ${metadata.status}.`);
    }
  }

  const publicStatus =
    lastStatus === "UNSAFE_ATTRIBUTION"
      ? "Street View-attribusjonen røpet for mye"
      : lastStatus === "USED_PANO"
        ? "alle gyldige Street View-panoramaer er brukt"
      : lastStatus || "ukjent status";
  throw new Error(`Ingen kurert SlowGeo-kandidat hadde gyldig Street View akkurat nå (${publicStatus}).`);
}
